// Auto-generated by appC_earlgrey/tools/reggen_actor.py
// Source: pwrmgr.hjson
// DO NOT EDIT: regenerate with `reggen_actor.py pwrmgr.hjson`

package pwrmgr_ral_defs_pkg;
  import actor_ral_pkg::*;

  function void define_pwrmgr_ral(RalActor ral);
    ral.define_reg("INTR_STATE", 32'h00000000, RAL_W1C, 32'h00000000);
    ral.define_field("INTR_STATE", "wakeup", 0, 1, RAL_RW, 32'h0);
    ral.define_reg("INTR_ENABLE", 32'h00000004, RAL_RW, 32'h00000000);
    ral.define_field("INTR_ENABLE", "wakeup", 0, 1, RAL_RW, 32'h0);
    ral.define_reg("INTR_TEST", 32'h00000008, RAL_WO, 32'h00000000);
    ral.define_field("INTR_TEST", "wakeup", 0, 1, RAL_WO, 32'h0);
    ral.define_reg("ALERT_TEST", 32'h0000000C, RAL_WO, 32'h00000000);
    ral.define_field("ALERT_TEST", "fatal_fault", 0, 1, RAL_WO, 32'h0);
    ral.define_reg("CTRL_CFG_REGWEN", 32'h00000010, RAL_RO, 32'h00000000);
    ral.define_field("CTRL_CFG_REGWEN", "EN", 0, 1, RAL_RO, 32'h1);
    ral.define_reg("CONTROL", 32'h00000014, RAL_RW, 32'h00000000);
    ral.define_field("CONTROL", "LOW_POWER_HINT", 0, 1, RAL_RW, 32'h0);
    ral.define_field("CONTROL", "CORE_CLK_EN", 4, 1, RAL_RW, 32'h0);
    ral.define_field("CONTROL", "IO_CLK_EN", 5, 1, RAL_RW, 32'h0);
    ral.define_field("CONTROL", "USB_CLK_EN_LP", 6, 1, RAL_RW, 32'h0);
    ral.define_field("CONTROL", "USB_CLK_EN_ACTIVE", 7, 1, RAL_RW, 32'h1);
    ral.define_field("CONTROL", "MAIN_PD_N", 8, 1, RAL_RW, 32'h1);
    ral.define_reg("CFG_CDC_SYNC", 32'h00000018, RAL_RW, 32'h00000000);
    ral.define_field("CFG_CDC_SYNC", "SYNC", 0, 1, RAL_RW, 32'h0);
    ral.define_reg("WAKEUP_EN_REGWEN", 32'h0000001C, RAL_W0C, 32'h00000000);
    ral.define_field("WAKEUP_EN_REGWEN", "EN", 0, 1, RAL_W0C, 32'h1);
    ral.define_reg("RESET_EN_REGWEN", 32'h00000020, RAL_W0C, 32'h00000000);
    ral.define_field("RESET_EN_REGWEN", "EN", 0, 1, RAL_W0C, 32'h1);
    ral.define_reg("RESET_EN", 32'h00000024, RAL_RW, 32'h00000000);
    ral.define_field("RESET_EN", "EN_0", 0, 1, RAL_RW, 32'h0);
    ral.define_field("RESET_EN", "EN_1", 1, 1, RAL_RW, 32'h0);
    ral.define_reg("ESCALATE_RESET_STATUS", 32'h00000028, RAL_RO, 32'h00000000);
    ral.define_field("ESCALATE_RESET_STATUS", "VAL", 0, 1, RAL_RO, 32'h0);
    ral.define_reg("WAKE_INFO_CAPTURE_DIS", 32'h0000002C, RAL_RW, 32'h00000000);
    ral.define_field("WAKE_INFO_CAPTURE_DIS", "VAL", 0, 1, RAL_RW, 32'h0);
    ral.define_reg("WAKE_INFO", 32'h00000030, RAL_W1C, 32'h00000000);
    ral.define_field("WAKE_INFO", "REASONS", 0, 6, RAL_W1C, 32'h0);
    ral.define_field("WAKE_INFO", "FALL_THROUGH", 6, 1, RAL_W1C, 32'h0);
    ral.define_field("WAKE_INFO", "ABORT", 7, 1, RAL_W1C, 32'h0);
    ral.define_reg("FAULT_STATUS", 32'h00000034, RAL_RO, 32'h00000000);
    ral.define_field("FAULT_STATUS", "REG_INTG_ERR", 0, 1, RAL_RO, 32'h0);
    ral.define_field("FAULT_STATUS", "ESC_TIMEOUT", 1, 1, RAL_RO, 32'h0);
    ral.define_field("FAULT_STATUS", "MAIN_PD_GLITCH", 2, 1, RAL_RO, 32'h0);
  endfunction
endpackage
