// GENERATED by build_bdd.py.  Unrank as package functions (shared by the
// class-based ConstraintActor in sim and, structurally, the RTL module on fabric).
package bdd_unrank_pkg;
  localparam logic [15:0] NSOL = 16'd416;
  localparam logic [15:0] SEED = 16'hACE1;
  localparam logic [15:0] TAPS = 16'hB400;
  localparam logic [4:0] ROOT = 5'd29;
  function automatic logic [4:0] f_lo(input logic [4:0] i);
    logic [4:0] r; case (i)
      5'd0: r = 5'd0;
      5'd1: r = 5'd1;
      5'd2: r = 5'd0;
      5'd3: r = 5'd2;
      5'd4: r = 5'd3;
      5'd5: r = 5'd4;
      5'd6: r = 5'd5;
      5'd7: r = 5'd1;
      5'd8: r = 5'd7;
      5'd9: r = 5'd8;
      5'd10: r = 5'd9;
      5'd11: r = 5'd10;
      5'd12: r = 5'd6;
      5'd13: r = 5'd11;
      5'd14: r = 5'd12;
      5'd15: r = 5'd6;
      5'd16: r = 5'd15;
      5'd17: r = 5'd14;
      5'd18: r = 5'd17;
      5'd19: r = 5'd16;
      5'd20: r = 5'd19;
      5'd21: r = 5'd18;
      5'd22: r = 5'd20;
      5'd23: r = 5'd21;
      5'd24: r = 5'd13;
      5'd25: r = 5'd14;
      5'd26: r = 5'd25;
      5'd27: r = 5'd26;
      5'd28: r = 5'd27;
      5'd29: r = 5'd23;
      default: r='0; endcase f_lo=r; endfunction
  function automatic logic [4:0] f_hi(input logic [4:0] i);
    logic [4:0] r; case (i)
      5'd0: r = 5'd0;
      5'd1: r = 5'd1;
      5'd2: r = 5'd0;
      5'd3: r = 5'd2;
      5'd4: r = 5'd3;
      5'd5: r = 5'd4;
      5'd6: r = 5'd5;
      5'd7: r = 5'd1;
      5'd8: r = 5'd7;
      5'd9: r = 5'd8;
      5'd10: r = 5'd9;
      5'd11: r = 5'd10;
      5'd12: r = 5'd11;
      5'd13: r = 5'd11;
      5'd14: r = 5'd13;
      5'd15: r = 5'd6;
      5'd16: r = 5'd15;
      5'd17: r = 5'd16;
      5'd18: r = 5'd17;
      5'd19: r = 5'd16;
      5'd20: r = 5'd19;
      5'd21: r = 5'd20;
      5'd22: r = 5'd20;
      5'd23: r = 5'd22;
      5'd24: r = 5'd13;
      5'd25: r = 5'd24;
      5'd26: r = 5'd19;
      5'd27: r = 5'd20;
      5'd28: r = 5'd22;
      5'd29: r = 5'd28;
      default: r='0; endcase f_hi=r; endfunction
  function automatic logic [15:0] f_clo(input logic [4:0] i);
    logic [15:0] r; case (i)
      5'd0: r = 16'd0;
      5'd1: r = 16'd1;
      5'd2: r = 16'd0;
      5'd3: r = 16'd0;
      5'd4: r = 16'd0;
      5'd5: r = 16'd0;
      5'd6: r = 16'd0;
      5'd7: r = 16'd1;
      5'd8: r = 16'd2;
      5'd9: r = 16'd4;
      5'd10: r = 16'd8;
      5'd11: r = 16'd16;
      5'd12: r = 16'd0;
      5'd13: r = 16'd32;
      5'd14: r = 16'd32;
      5'd15: r = 16'd0;
      5'd16: r = 16'd0;
      5'd17: r = 16'd96;
      5'd18: r = 16'd96;
      5'd19: r = 16'd0;
      5'd20: r = 16'd0;
      5'd21: r = 16'd192;
      5'd22: r = 16'd0;
      5'd23: r = 16'd192;
      5'd24: r = 16'd64;
      5'd25: r = 16'd96;
      5'd26: r = 16'd224;
      5'd27: r = 16'd224;
      5'd28: r = 16'd224;
      5'd29: r = 16'd192;
      default: r='0; endcase f_clo=r; endfunction
  function automatic logic [3:0] f_ord(input logic [3:0] lvl);
    logic [3:0] r; case (lvl)
      4'd0: r = 4'd8;
      4'd1: r = 4'd0;
      4'd2: r = 4'd1;
      4'd3: r = 4'd7;
      4'd4: r = 4'd11;
      4'd5: r = 4'd9;
      4'd6: r = 4'd10;
      4'd7: r = 4'd2;
      4'd8: r = 4'd3;
      4'd9: r = 4'd4;
      4'd10: r = 4'd5;
      4'd11: r = 4'd6;
      default: r='0; endcase f_ord=r; endfunction
  function automatic logic [15:0] lfsr_step(input logic [15:0] s);
    lfsr_step = (s >> 1) ^ (s[0] ? TAPS : 16'h0); endfunction
  function automatic logic [11:0] bdd_unrank(input logic [15:0] lfsr_val);
    logic [15:0] R; logic [4:0] idx; logic [11:0] acc; logic [15:0] clo;
    R = lfsr_val % NSOL; idx = ROOT; acc = '0;
    for (int level=0; level<12; level++) begin
      clo = f_clo(idx);
      if (R < clo) begin acc[f_ord(level[3:0])]=1'b0; idx=f_lo(idx); end
      else         begin acc[f_ord(level[3:0])]=1'b1; R=R-clo; idx=f_hi(idx); end
    end
    return acc;
  endfunction
endpackage
