/-
  Codegen.lean — 05_lean_certified / L4: CERTIFIED CODEGEN.  Lean emits the
  SystemVerilog sampler from the SAME `legal` set its theorems certify, so the
  RTL is faithful to the certified model BY CONSTRUCTION.  Then verilator
  validates it (synthesizable + bit-identical) and yosys gives the area — the
  SV-constraint → FPGA loop, closed and certified.

  Emits PACKED-vector RTL (one `[NV*VW-1:0]` bus, v0 in the MSBs) so it
  synthesizes on BOTH verilator and yosys.  Imports the L2 Sampler.
  Run:  LEAN_PATH=. lean Codegen.lean   (writes .sv).
-/
import Sampler
open Sampler

namespace Codegen

/-- bit width to hold values 0..n. -/
def bw (n : Nat) : Nat := if n == 0 then 1 else Nat.log2 n + 1

def withIdx {α} (l : List α) : List (Nat × α) := (List.range l.length).zip l

/-- one `case` arm per legal assignment: idx → out = {v0,v1,…} (v0 in MSBs). -/
def romArms (vw : Nat) (entries : List Asn) : String :=
  String.join <| (withIdx entries).map fun (i, e) =>
    let vals := String.intercalate ", " (e.map (fun val => s!"{vw}'d{val}"))
    s!"      {i}: out = " ++ "{" ++ vals ++ "};\n"

/-- the Tier-1 unrank sampler: a combinational ROM indexed by `idx`, packed bus. -/
def emitSampler (nv vw iw : Nat) (entries : List Asn) : String :=
s!"// GENERATED by 05_lean_certified Codegen.lean from a Lean-CERTIFIED legal set.
// Tier-1 unrank: out = legalSet[idx] (packed, v0 in MSBs). Synthesizable ROM.
module tier1_sampler #(parameter int unsigned NV={nv}, VW={vw}, IW={iw}, OW={nv*vw})
  (input  logic [IW-1:0] idx,
   output logic [OW-1:0] out);
  always_comb begin
    out = '0;
    case (idx)
{romArms vw entries}      default: ;
    endcase
  end
endmodule
"

/-- the constraint INDEPENDENTLY coded in SV (all-different ∧ sum==S ∧ v0<v1),
    reading the packed bus.  The checker the sampler output must pass. -/
def emitChecker (nv vw sum : Nat) : String :=
s!"// the constraint as a synthesizable checker (independent of the ROM).
module tier1_checker #(parameter int unsigned NV={nv}, VW={vw}, SUM={sum}, OW={nv*vw})
  (input logic [OW-1:0] inp, output logic ok);
  always_comb begin
    logic ad; int unsigned s; logic [VW-1:0] vi, vj;
    ad = 1'b1; s = 0;
    for (int i=0;i<NV;i++) begin
      vi = inp[(NV-1-i)*VW +: VW];
      s += vi;
      for (int j=i+1;j<NV;j++) begin
        vj = inp[(NV-1-j)*VW +: VW];
        if (vi==vj) ad = 1'b0;
      end
    end
    ok = ad && (s==SUM) && (inp[(NV-1)*VW +: VW] < inp[(NV-2)*VW +: VW]);
  end
endmodule
"

/-- self-checking tb: for every index, the ROM output must (a) pass the SV
    checker and (b) equal the expected Lean entry (packed). -/
def emitTb (nv vw n : Nat) (entries : List Asn) : String :=
  let expRows := String.join <| (withIdx entries).map fun (i, e) =>
    let vals := String.intercalate ", " (e.map (fun x => s!"{vw}'d{x}"))
    s!"    exp[{i}] = " ++ "{" ++ vals ++ "};\n"
s!"// GENERATED self-checking tb: SV sampler ≡ Lean-certified legal set.
module tb_top;
  localparam int unsigned NV={nv}, VW={vw}, N={n}, IW={bw (n-1)}, OW={nv*vw};
  logic [IW-1:0] idx; logic [OW-1:0] out; logic ok;
  logic [OW-1:0] exp [0:N-1];
  tier1_sampler #(.NV(NV),.VW(VW),.IW(IW)) dut(.idx(idx), .out(out));
  tier1_checker #(.NV(NV),.VW(VW)) chk(.inp(out), .ok(ok));
  initial begin
    static int bad = 0;
{expRows}    for (int i=0;i<N;i++) begin
      idx = i[IW-1:0]; #1;
      if (!ok) begin bad++; $display(\"  idx %0d: checker REJECTED\", i); end
      if (out !== exp[i]) begin bad++; $display(\"  idx %0d: out %0h != exp %0h\", i, out, exp[i]); end
    end
    if (bad==0) $display(\">>> L4 OK: Tier-1 SV sampler == Lean-certified legal set, all pass the SV checker (N=%0d)\", N);
    else        $display(\">>> L4 FAIL: %0d mismatches\", bad);
    $finish;
  end
endmodule
"

-- instantiate on the L2 certified constraint (3 vars [1,4], all-diff, sum==6, v0<v1)
def entries : List Asn := legal Pinst domsInst
def NV : Nat := 3
def VW : Nat := bw 4
def N  : Nat := entries.length
def IW : Nat := bw (N - 1)

#eval do
  IO.FS.writeFile "tier1_sampler.sv" (emitSampler NV VW IW entries)
  IO.FS.writeFile "tier1_checker.sv" (emitChecker NV VW 6)
  IO.FS.writeFile "tb_tier1.sv"      (emitTb NV VW N entries)
  IO.println s!"emitted tier1_*.sv  (N={N}, legal={entries})"

end Codegen
