// GENERATED by 05_lean_certified Codegen.lean from a Lean-CERTIFIED legal set.
// Tier-1 unrank: out = legalSet[idx] (packed, v0 in MSBs). Synthesizable ROM.
module tier1_sampler #(parameter int unsigned NV=3, VW=3, IW=2, OW=9)
  (input  logic [IW-1:0] idx,
   output logic [OW-1:0] out);
  always_comb begin
    out = '0;
    case (idx)
      0: out = {3'd1, 3'd2, 3'd3};
      1: out = {3'd1, 3'd3, 3'd2};
      2: out = {3'd2, 3'd3, 3'd1};
      default: ;
    endcase
  end
endmodule
