// GENERATED by 05_lean_certified Codegen.lean from a Lean-CERTIFIED legal set.
// Tier-1 unrank: out = legalSet[idx] (packed, v0 in MSBs). Synthesizable ROM.
module tier1_sampler #(parameter int unsigned NV=3, VW=3, IW=6, OW=9)
  (input  logic [IW-1:0] idx,
   output logic [OW-1:0] out);
  always_comb begin
    out = '0;
    case (idx)
      0: out = {3'd1, 3'd2, 3'd3};
      1: out = {3'd1, 3'd2, 3'd4};
      2: out = {3'd1, 3'd2, 3'd5};
      3: out = {3'd1, 3'd3, 3'd2};
      4: out = {3'd1, 3'd3, 3'd4};
      5: out = {3'd1, 3'd3, 3'd5};
      6: out = {3'd1, 3'd4, 3'd2};
      7: out = {3'd1, 3'd4, 3'd3};
      8: out = {3'd1, 3'd4, 3'd5};
      9: out = {3'd1, 3'd5, 3'd2};
      10: out = {3'd1, 3'd5, 3'd3};
      11: out = {3'd1, 3'd5, 3'd4};
      12: out = {3'd2, 3'd1, 3'd3};
      13: out = {3'd2, 3'd1, 3'd4};
      14: out = {3'd2, 3'd1, 3'd5};
      15: out = {3'd2, 3'd3, 3'd1};
      16: out = {3'd2, 3'd3, 3'd4};
      17: out = {3'd2, 3'd3, 3'd5};
      18: out = {3'd2, 3'd4, 3'd1};
      19: out = {3'd2, 3'd4, 3'd3};
      20: out = {3'd2, 3'd4, 3'd5};
      21: out = {3'd2, 3'd5, 3'd1};
      22: out = {3'd2, 3'd5, 3'd3};
      23: out = {3'd2, 3'd5, 3'd4};
      24: out = {3'd3, 3'd1, 3'd2};
      25: out = {3'd3, 3'd1, 3'd4};
      26: out = {3'd3, 3'd1, 3'd5};
      27: out = {3'd3, 3'd2, 3'd1};
      28: out = {3'd3, 3'd2, 3'd4};
      29: out = {3'd3, 3'd2, 3'd5};
      30: out = {3'd3, 3'd4, 3'd1};
      31: out = {3'd3, 3'd4, 3'd2};
      32: out = {3'd3, 3'd4, 3'd5};
      33: out = {3'd3, 3'd5, 3'd1};
      34: out = {3'd3, 3'd5, 3'd2};
      35: out = {3'd3, 3'd5, 3'd4};
      36: out = {3'd4, 3'd1, 3'd2};
      37: out = {3'd4, 3'd1, 3'd3};
      38: out = {3'd4, 3'd1, 3'd5};
      39: out = {3'd4, 3'd2, 3'd1};
      40: out = {3'd4, 3'd2, 3'd3};
      41: out = {3'd4, 3'd2, 3'd5};
      42: out = {3'd4, 3'd3, 3'd1};
      43: out = {3'd4, 3'd3, 3'd2};
      44: out = {3'd4, 3'd3, 3'd5};
      45: out = {3'd4, 3'd5, 3'd1};
      46: out = {3'd4, 3'd5, 3'd2};
      47: out = {3'd4, 3'd5, 3'd3};
      48: out = {3'd5, 3'd1, 3'd2};
      49: out = {3'd5, 3'd1, 3'd3};
      50: out = {3'd5, 3'd1, 3'd4};
      51: out = {3'd5, 3'd2, 3'd1};
      52: out = {3'd5, 3'd2, 3'd3};
      53: out = {3'd5, 3'd2, 3'd4};
      54: out = {3'd5, 3'd3, 3'd1};
      55: out = {3'd5, 3'd3, 3'd2};
      56: out = {3'd5, 3'd3, 3'd4};
      57: out = {3'd5, 3'd4, 3'd1};
      58: out = {3'd5, 3'd4, 3'd2};
      59: out = {3'd5, 3'd4, 3'd3};
      default: ;
    endcase
  end
endmodule
