// GENERATED by 05_lean_certified Codegen.lean from a Lean-CERTIFIED legal set.
// Tier-1 unrank: out = legalSet[idx] (packed, v0 in MSBs). Synthesizable ROM.
module tier1_sampler #(parameter int unsigned NV=3, VW=5, IW=6, OW=15)
  (input  logic [IW-1:0] idx,
   output logic [OW-1:0] out);
  always_comb begin
    out = '0;
    case (idx)
      0: out = {5'd0, 5'd4, 5'd1};
      1: out = {5'd0, 5'd4, 5'd2};
      2: out = {5'd0, 5'd4, 5'd3};
      3: out = {5'd0, 5'd8, 5'd1};
      4: out = {5'd0, 5'd8, 5'd2};
      5: out = {5'd0, 5'd8, 5'd3};
      6: out = {5'd0, 5'd12, 5'd1};
      7: out = {5'd0, 5'd12, 5'd2};
      8: out = {5'd0, 5'd12, 5'd3};
      9: out = {5'd4, 5'd0, 5'd1};
      10: out = {5'd4, 5'd0, 5'd2};
      11: out = {5'd4, 5'd0, 5'd3};
      12: out = {5'd4, 5'd8, 5'd1};
      13: out = {5'd4, 5'd8, 5'd2};
      14: out = {5'd4, 5'd8, 5'd3};
      15: out = {5'd4, 5'd12, 5'd1};
      16: out = {5'd4, 5'd12, 5'd2};
      17: out = {5'd4, 5'd12, 5'd3};
      18: out = {5'd8, 5'd0, 5'd1};
      19: out = {5'd8, 5'd0, 5'd2};
      20: out = {5'd8, 5'd0, 5'd3};
      21: out = {5'd8, 5'd4, 5'd1};
      22: out = {5'd8, 5'd4, 5'd2};
      23: out = {5'd8, 5'd4, 5'd3};
      24: out = {5'd8, 5'd12, 5'd1};
      25: out = {5'd8, 5'd12, 5'd2};
      26: out = {5'd8, 5'd12, 5'd3};
      27: out = {5'd12, 5'd0, 5'd1};
      28: out = {5'd12, 5'd0, 5'd2};
      29: out = {5'd12, 5'd0, 5'd3};
      30: out = {5'd12, 5'd4, 5'd1};
      31: out = {5'd12, 5'd4, 5'd2};
      32: out = {5'd12, 5'd4, 5'd3};
      33: out = {5'd12, 5'd8, 5'd1};
      34: out = {5'd12, 5'd8, 5'd2};
      35: out = {5'd12, 5'd8, 5'd3};
      default: ;
    endcase
  end
endmodule
