#!/usr/bin/env python3
"""
reggen_actor.py -- emit a SystemVerilog define_*_ral() body from an
OpenTitan-style register Hjson description.

The actor-framework analogue of OpenTitan's reggen UVM-RAL output. Output is a
single SV file per IP that the per-IP env imports and calls from its
constructor:

    import my_ip_ral_defs::*;
    ...
    define_my_ip_ral(ral);

Usage:
    tools/reggen_actor.py path/to/ip.hjson > my_ip_ral_defs.sv
    tools/reggen_actor.py path/to/ip.hjson --pkg my_ip_ral_defs > my_ip_ral_defs.sv

Hjson format supported (compatible with OpenTitan's reggen input):

    {
      name: "uart"
      regwidth: 32
      registers: [
        { name: "INTR_STATE", swaccess: "rw1c", resval: 0
          fields: [
            { bits: "0", name: "tx_watermark" }
            { bits: "1", name: "rx_watermark" }
          ]
        }
        ...
      ]
    }

Multi-byte register layouts and skipto directives are honored. Unknown
keys are ignored. If hjson is installed it is used; otherwise the file
must be valid JSON.
"""

import argparse
import json
import re
import sys

try:
    import hjson
    def parse_file(path):
        with open(path) as f:
            return hjson.load(f)
except ImportError:
    def parse_file(path):
        with open(path) as f:
            return json.load(f)


ACCESS_MAP = {
    "rw":   "RAL_RW",
    "ro":   "RAL_RO",
    "wo":   "RAL_WO",
    "rc":   "RAL_RC",
    "rw1c": "RAL_W1C",
    "w1c":  "RAL_W1C",
    "rw0c": "RAL_W0C",
    "w0c":  "RAL_W0C",
    "r0w1c": "RAL_W1C",
}


def sv_access(s):
    if s is None:
        return "RAL_RW"
    return ACCESS_MAP.get(str(s).lower(), "RAL_RW")


def parse_bits(bits_str):
    """'7:0' -> (lsb=0, width=8); '5' -> (5, 1).

    Falls back to (0, 32) for parameterized expressions like 'HashCntW-1:0'
    that the tool cannot resolve without knowing parameter values; the
    user can hand-edit the generated file in those cases.
    """
    s = str(bits_str).strip()
    m = re.match(r'^(\d+)\s*:\s*(\d+)$', s)
    if m:
        msb, lsb = int(m.group(1)), int(m.group(2))
        return lsb, msb - lsb + 1
    try:
        return int(s), 1
    except ValueError:
        return 0, 32     # full-word fallback for parameterized fields


def emit(spec, fn_name, pkg_name):
    out = []
    src = spec.get('name', 'unknown')

    out.append(f"// Auto-generated by appC_earlgrey/tools/reggen_actor.py")
    out.append(f"// Source: {src}.hjson")
    out.append(f"// DO NOT EDIT: regenerate with `reggen_actor.py {src}.hjson`")
    out.append("")
    if pkg_name:
        out.append(f"package {pkg_name};")
        out.append("  import actor_ral_pkg::*;")
        out.append("")
    indent = "  " if pkg_name else ""
    out.append(f"{indent}function void {fn_name}(RalActor ral);")

    def to_int(v, default=0):
        if v is None:
            return default
        if isinstance(v, int):
            return v
        try:
            return int(str(v), 0)
        except ValueError:
            return default

    addr = to_int(spec.get('reg_baseaddr', 0))
    word_size = to_int(spec.get('regwidth', 32)) // 8

    # `registers` may be a flat list (single bus interface) or a dict
    # keyed by interface name (multiple TL-UL ports). Take the first
    # interface in the dict case.
    raw_regs = spec.get('registers', [])
    if isinstance(raw_regs, dict):
        # Pick the first interface's register list
        for iface_name, iface_regs in raw_regs.items():
            if isinstance(iface_regs, list):
                raw_regs = iface_regs
                break
        else:
            raw_regs = []

    # OpenTitan reggen synthesizes INTR_STATE/INTR_ENABLE/INTR_TEST for
    # any IP that declares an `interrupt_list`, and ALERT_TEST for any IP
    # that declares an `alert_list`. The hjson does NOT spell those four
    # registers out; reggen's UVM-RAL generator infers them. We do the same.
    # These come first in the address map (offsets 0x0..0xC) followed by
    # whatever the IP declared in `registers:`.
    auto_regs = []
    intr_list = spec.get('interrupt_list') or []
    if intr_list and not spec.get('no_auto_intr_regs'):
        intr_fields = []
        for i, intr in enumerate(intr_list):
            if isinstance(intr, dict) and 'name' in intr:
                intr_fields.append({
                    'name':     intr['name'],
                    'bits':     str(i),
                    'swaccess': 'rw',
                    'resval':   to_int(intr.get('default', 0)),
                })
        auto_regs.append({
            'name':     'INTR_STATE',
            'swaccess': 'rw1c',
            'resval':   0,
            'fields':   intr_fields,
        })
        auto_regs.append({
            'name':     'INTR_ENABLE',
            'swaccess': 'rw',
            'resval':   0,
            'fields':   [dict(f, swaccess='rw') for f in intr_fields],
        })
        auto_regs.append({
            'name':     'INTR_TEST',
            'swaccess': 'wo',
            'resval':   0,
            'fields':   [dict(f, swaccess='wo') for f in intr_fields],
        })

    alert_list = spec.get('alert_list') or []
    if alert_list and not spec.get('no_auto_alert_regs'):
        alert_fields = []
        for i, al in enumerate(alert_list):
            if isinstance(al, dict) and 'name' in al:
                alert_fields.append({
                    'name':     al['name'],
                    'bits':     str(i),
                    'swaccess': 'wo',
                    'resval':   0,
                })
        auto_regs.append({
            'name':     'ALERT_TEST',
            'swaccess': 'wo',
            'resval':   0,
            'fields':   alert_fields,
        })

    raw_regs = auto_regs + list(raw_regs)

    # Expand `multireg` entries into a flat sequence of register dicts.
    # A multireg with count=N expands to N register instances named
    # NAME_0 .. NAME_{N-1} at consecutive offsets.
    expanded = []
    for reg in raw_regs:
        if isinstance(reg, dict) and 'multireg' in reg:
            mr      = reg['multireg']
            base    = mr.get('name', 'MULTIREG')
            count   = to_int(mr.get('count', 1))
            sw      = mr.get('swaccess', 'rw')
            resval  = mr.get('resval', 0)
            fields  = mr.get('fields', [])
            for i in range(count):
                clone = {
                    'name':     f"{base}_{i}",
                    'swaccess': sw,
                    'resval':   resval,
                    'fields':   fields,
                }
                expanded.append(clone)
        else:
            expanded.append(reg)

    for reg in expanded:
        # Skip non-register entries (skipto markers, reserved, multireg
        # expansions are handled separately in real reggen; we accept
        # the simple flat form here)
        if isinstance(reg, dict) and 'skipto' in reg:
            try:
                addr = int(reg['skipto'], 0)
            except (ValueError, TypeError):
                pass
            continue
        if isinstance(reg, dict) and 'reserved' in reg:
            n = int(reg.get('reserved', 1))
            addr += n * word_size
            continue
        if not isinstance(reg, dict) or 'name' not in reg:
            continue

        name    = reg['name']
        access  = sv_access(reg.get('swaccess', 'rw'))
        reset   = to_int(reg.get('resval', 0))

        out.append(f"{indent}  ral.define_reg(\"{name}\", "
                   f"32'h{addr:08X}, {access}, 32'h{reset:08X});")

        for field in reg.get('fields', []):
            if not isinstance(field, dict) or 'name' not in field:
                continue
            f_name = field['name']
            f_lsb, f_width = parse_bits(field.get('bits', '0'))
            f_access = sv_access(field.get('swaccess', reg.get('swaccess', 'rw')))
            f_reset = to_int(field.get('resval', 0))
            out.append(f"{indent}  ral.define_field(\"{name}\", "
                       f"\"{f_name}\", {f_lsb}, {f_width}, "
                       f"{f_access}, 32'h{f_reset:X});")

        addr += word_size

    # Memories declared in a separate top-level "memory" or "memory_regions" key
    for mem in spec.get('memories', []):
        if not isinstance(mem, dict) or 'name' not in mem:
            continue
        m_name = mem['name']
        m_base = to_int(mem.get('base_addr', 0))
        m_size = to_int(mem.get('size_bytes', 0))
        m_root = mem.get('backdoor_root', '')
        out.append(f"{indent}  ral.define_mem(\"{m_name}\", "
                   f"32'h{m_base:08X}, {m_size}, \"{m_root}\");")

    out.append(f"{indent}endfunction")
    if pkg_name:
        out.append("endpackage")
    return "\n".join(out) + "\n"


def main():
    p = argparse.ArgumentParser(description=__doc__,
                                formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument('hjson_file')
    p.add_argument('--fn-name', default=None,
                   help='Function name (default: define_<ip>_ral)')
    p.add_argument('--pkg', default=None,
                   help='Wrap the function in a package by this name')
    args = p.parse_args()

    spec = parse_file(args.hjson_file)
    fn = args.fn_name or f"define_{spec.get('name', 'ip')}_ral"
    sys.stdout.write(emit(spec, fn, args.pkg))


if __name__ == '__main__':
    main()
