// Auto-generated by appC_earlgrey/tools/reggen_actor.py
// Source: rstmgr.hjson
// DO NOT EDIT: regenerate with `reggen_actor.py rstmgr.hjson`

package rstmgr_ral_defs_pkg;
  import actor_ral_pkg::*;

  function void define_rstmgr_ral(RalActor ral);
    ral.define_reg("ALERT_TEST", 32'h00000000, RAL_WO, 32'h00000000);
    ral.define_field("ALERT_TEST", "fatal_fault", 0, 1, RAL_WO, 32'h0);
    ral.define_field("ALERT_TEST", "fatal_cnsty_fault", 1, 1, RAL_WO, 32'h0);
    ral.define_reg("RESET_REQ", 32'h00000004, RAL_RW, 32'h00000000);
    ral.define_field("RESET_REQ", "VAL", 0, 4, RAL_RW, 32'h0);
    ral.define_reg("RESET_INFO", 32'h00000008, RAL_W1C, 32'h00000000);
    ral.define_field("RESET_INFO", "POR", 0, 1, RAL_W1C, 32'h1);
    ral.define_field("RESET_INFO", "LOW_POWER_EXIT", 1, 1, RAL_W1C, 32'h0);
    ral.define_field("RESET_INFO", "SW_RESET", 2, 1, RAL_W1C, 32'h0);
    ral.define_field("RESET_INFO", "HW_REQ", 3, 5, RAL_W1C, 32'h0);
    ral.define_reg("ALERT_REGWEN", 32'h0000000C, RAL_W0C, 32'h00000000);
    ral.define_field("ALERT_REGWEN", "EN", 0, 1, RAL_W0C, 32'h1);
    ral.define_reg("ALERT_INFO_CTRL", 32'h00000010, RAL_RW, 32'h00000000);
    ral.define_field("ALERT_INFO_CTRL", "EN", 0, 1, RAL_RW, 32'h0);
    ral.define_field("ALERT_INFO_CTRL", "INDEX", 0, 32, RAL_RW, 32'h0);
    ral.define_reg("ALERT_INFO_ATTR", 32'h00000014, RAL_RO, 32'h00000000);
    ral.define_field("ALERT_INFO_ATTR", "CNT_AVAIL", 0, 32, RAL_RO, 32'h0);
    ral.define_reg("ALERT_INFO", 32'h00000018, RAL_RO, 32'h00000000);
    ral.define_field("ALERT_INFO", "VALUE", 0, 32, RAL_RO, 32'h0);
    ral.define_reg("CPU_REGWEN", 32'h0000001C, RAL_W0C, 32'h00000000);
    ral.define_field("CPU_REGWEN", "EN", 0, 1, RAL_W0C, 32'h1);
    ral.define_reg("CPU_INFO_CTRL", 32'h00000020, RAL_RW, 32'h00000000);
    ral.define_field("CPU_INFO_CTRL", "EN", 0, 1, RAL_RW, 32'h0);
    ral.define_field("CPU_INFO_CTRL", "INDEX", 0, 32, RAL_RW, 32'h0);
    ral.define_reg("CPU_INFO_ATTR", 32'h00000024, RAL_RO, 32'h00000000);
    ral.define_field("CPU_INFO_ATTR", "CNT_AVAIL", 0, 32, RAL_RO, 32'h0);
    ral.define_reg("CPU_INFO", 32'h00000028, RAL_RO, 32'h00000000);
    ral.define_field("CPU_INFO", "VALUE", 0, 32, RAL_RO, 32'h0);
    ral.define_reg("ERR_CODE", 32'h0000002C, RAL_RO, 32'h00000000);
    ral.define_field("ERR_CODE", "REG_INTG_ERR", 0, 1, RAL_RO, 32'h0);
    ral.define_field("ERR_CODE", "RESET_CONSISTENCY_ERR", 1, 1, RAL_RO, 32'h0);
    ral.define_field("ERR_CODE", "FSM_ERR", 2, 1, RAL_RO, 32'h0);
  endfunction
endpackage
