// Auto-generated by appC_earlgrey/tools/reggen_actor.py
// Source: otbn.hjson
// DO NOT EDIT: regenerate with `reggen_actor.py otbn.hjson`

package otbn_ral_defs_pkg;
  import actor_ral_pkg::*;

  function void define_otbn_ral(RalActor ral);
    ral.define_reg("INTR_STATE", 32'h00000000, RAL_W1C, 32'h00000000);
    ral.define_field("INTR_STATE", "done", 0, 1, RAL_RW, 32'h0);
    ral.define_reg("INTR_ENABLE", 32'h00000004, RAL_RW, 32'h00000000);
    ral.define_field("INTR_ENABLE", "done", 0, 1, RAL_RW, 32'h0);
    ral.define_reg("INTR_TEST", 32'h00000008, RAL_WO, 32'h00000000);
    ral.define_field("INTR_TEST", "done", 0, 1, RAL_WO, 32'h0);
    ral.define_reg("ALERT_TEST", 32'h0000000C, RAL_WO, 32'h00000000);
    ral.define_field("ALERT_TEST", "fatal", 0, 1, RAL_WO, 32'h0);
    ral.define_field("ALERT_TEST", "recov", 1, 1, RAL_WO, 32'h0);
    ral.define_reg("CMD", 32'h00000010, RAL_WO, 32'h00000000);
    ral.define_field("CMD", "cmd", 0, 8, RAL_WO, 32'h0);
    ral.define_reg("CTRL", 32'h00000014, RAL_RW, 32'h00000000);
    ral.define_field("CTRL", "software_errs_fatal", 0, 1, RAL_RW, 32'h0);
    ral.define_reg("STATUS", 32'h00000018, RAL_RO, 32'h00000000);
    ral.define_field("STATUS", "status", 0, 8, RAL_RO, 32'h4);
    ral.define_reg("ERR_BITS", 32'h0000001C, RAL_RW, 32'h00000000);
    ral.define_field("ERR_BITS", "bad_data_addr", 0, 1, RAL_RW, 32'h0);
    ral.define_field("ERR_BITS", "bad_insn_addr", 1, 1, RAL_RW, 32'h0);
    ral.define_field("ERR_BITS", "call_stack", 2, 1, RAL_RW, 32'h0);
    ral.define_field("ERR_BITS", "illegal_insn", 3, 1, RAL_RW, 32'h0);
    ral.define_field("ERR_BITS", "loop", 4, 1, RAL_RW, 32'h0);
    ral.define_field("ERR_BITS", "key_invalid", 5, 1, RAL_RW, 32'h0);
    ral.define_field("ERR_BITS", "rnd_rep_chk_fail", 6, 1, RAL_RW, 32'h0);
    ral.define_field("ERR_BITS", "rnd_fips_chk_fail", 7, 1, RAL_RW, 32'h0);
    ral.define_field("ERR_BITS", "imem_intg_violation", 16, 1, RAL_RW, 32'h0);
    ral.define_field("ERR_BITS", "dmem_intg_violation", 17, 1, RAL_RW, 32'h0);
    ral.define_field("ERR_BITS", "reg_intg_violation", 18, 1, RAL_RW, 32'h0);
    ral.define_field("ERR_BITS", "bus_intg_violation", 19, 1, RAL_RW, 32'h0);
    ral.define_field("ERR_BITS", "bad_internal_state", 20, 1, RAL_RW, 32'h0);
    ral.define_field("ERR_BITS", "illegal_bus_access", 21, 1, RAL_RW, 32'h0);
    ral.define_field("ERR_BITS", "lifecycle_escalation", 22, 1, RAL_RW, 32'h0);
    ral.define_field("ERR_BITS", "fatal_software", 23, 1, RAL_RW, 32'h0);
    ral.define_reg("FATAL_ALERT_CAUSE", 32'h00000020, RAL_RO, 32'h00000000);
    ral.define_field("FATAL_ALERT_CAUSE", "imem_intg_violation", 0, 1, RAL_RO, 32'h0);
    ral.define_field("FATAL_ALERT_CAUSE", "dmem_intg_violation", 1, 1, RAL_RO, 32'h0);
    ral.define_field("FATAL_ALERT_CAUSE", "reg_intg_violation", 2, 1, RAL_RO, 32'h0);
    ral.define_field("FATAL_ALERT_CAUSE", "bus_intg_violation", 3, 1, RAL_RO, 32'h0);
    ral.define_field("FATAL_ALERT_CAUSE", "bad_internal_state", 4, 1, RAL_RO, 32'h0);
    ral.define_field("FATAL_ALERT_CAUSE", "illegal_bus_access", 5, 1, RAL_RO, 32'h0);
    ral.define_field("FATAL_ALERT_CAUSE", "lifecycle_escalation", 6, 1, RAL_RO, 32'h0);
    ral.define_field("FATAL_ALERT_CAUSE", "fatal_software", 7, 1, RAL_RO, 32'h0);
    ral.define_reg("INSN_CNT", 32'h00000024, RAL_RW, 32'h00000000);
    ral.define_field("INSN_CNT", "insn_cnt", 0, 32, RAL_RW, 32'h0);
    ral.define_reg("LOAD_CHECKSUM", 32'h00000028, RAL_RW, 32'h00000000);
    ral.define_field("LOAD_CHECKSUM", "checksum", 0, 32, RAL_RW, 32'h0);
  endfunction
endpackage
