// GENERATED by csc.py -- self-checking testbench (checker = the constraint).
module tb_top;
  logic clk=0, rst_n=0, req=0, v; logic [10:0] s;
  localparam int N=200000;
  csc_sampler dut(.clk,.rst_n,.req,.valid(v),.sample_o(s));
  always #5 clk=~clk;
  function automatic bit legal(input logic [10:0] sample);
    automatic logic [0:0] fix_sp = sample[0:0];
    automatic logic [4:0] sp = sample[5:1];
    automatic logic [4:0] tp = sample[10:6];
    legal = (((!fix_sp) || (1 && (sp == 2)))) && ((sp != tp)) && ((!(((sp == 3) || (sp == 1)) || (sp == 0)))) && ((!(((tp == 3) || (tp == 1)) || (tp == 0))));
  endfunction
  integer i, n=0, bad=0; bit seen [int];
  initial begin
    rst_n=0; repeat(3)@(posedge clk); rst_n=1; @(posedge clk); req=1;
    while(n<N) begin @(posedge clk); if(v) begin
      n++; if(!legal(s)) bad++; seen[s]=1; end end
    $display("checked=%0d illegal=%0d distinct=%0d / nsol=840", n, bad, seen.size());
    if(bad==0 && seen.size()==840)
      $display(">>> csc: all legal AND full coverage (840 solutions)");
    $finish;
  end
endmodule
