// GENERATED by csc.py -- Tier-1 BDD unrank sampler.
module csc_sampler (input logic clk, rst_n, req, output logic valid,
  output logic [4:0] sample_o);
  localparam logic [15:0] NSOL=16'd28, SEED=16'hACE1, TAPS=16'hB400;
  localparam logic [3:0] ROOT=4'd11;
  function automatic logic [3:0] f_lo(input logic [3:0] i);
    logic [3:0] r; case(i)
      4'd0: r = 4'd0;
      4'd1: r = 4'd1;
      4'd2: r = 4'd0;
      4'd3: r = 4'd1;
      4'd4: r = 4'd2;
      4'd5: r = 4'd4;
      4'd6: r = 4'd3;
      4'd7: r = 4'd4;
      4'd8: r = 4'd5;
      4'd9: r = 4'd6;
      4'd10: r = 4'd9;
      4'd11: r = 4'd8;
      default: r='0; endcase f_lo=r; endfunction
  function automatic logic [3:0] f_hi(input logic [3:0] i);
    logic [3:0] r; case(i)
      4'd0: r = 4'd0;
      4'd1: r = 4'd1;
      4'd2: r = 4'd1;
      4'd3: r = 4'd1;
      4'd4: r = 4'd3;
      4'd5: r = 4'd4;
      4'd6: r = 4'd3;
      4'd7: r = 4'd6;
      4'd8: r = 4'd7;
      4'd9: r = 4'd6;
      4'd10: r = 4'd7;
      4'd11: r = 4'd10;
      default: r='0; endcase f_hi=r; endfunction
  function automatic logic [15:0] f_clo(input logic [3:0] i);
    logic [15:0] r; case(i)
      4'd0: r = 16'd0;
      4'd1: r = 16'd1;
      4'd2: r = 16'd0;
      4'd3: r = 16'd1;
      4'd4: r = 16'd1;
      4'd5: r = 16'd3;
      4'd6: r = 16'd2;
      4'd7: r = 16'd3;
      4'd8: r = 16'd6;
      4'd9: r = 16'd4;
      4'd10: r = 16'd8;
      4'd11: r = 16'd13;
      default: r='0; endcase f_clo=r; endfunction
  function automatic logic [15:0] lstep(input logic [15:0] s);
    lstep=(s>>1)^(s[0]?TAPS:16'h0); endfunction
  typedef enum logic [1:0] {IDLE,WALK,EMIT} st_e; st_e st;
  logic [15:0] lfsr,R; logic [3:0] idx; logic [4:0] lvl; logic [4:0] acc;
  logic [15:0] clo_c; logic bitc; assign clo_c=f_clo(idx); assign bitc=(R>=clo_c);
  always_ff @(posedge clk or negedge rst_n) if(!rst_n) begin
      st<=IDLE; lfsr<=SEED; valid<=0; sample_o<='0; idx<='0; R<='0; lvl<='0; acc<='0;
    end else begin valid<=0; case(st)
      IDLE: if(req) begin R<=lfsr%NSOL; idx<=ROOT; lvl<='0; acc<='0; st<=WALK; end
      WALK: begin acc[lvl[2:0]]<=bitc; idx<=bitc?f_hi(idx):f_lo(idx);
                  R<=bitc?(R-clo_c):R; lvl<=lvl+5'd1;
                  if(lvl==5'd4) st<=EMIT; end
      EMIT: begin sample_o<=acc; valid<=1; lfsr<=lstep(lfsr); st<=IDLE; end
      default: st<=IDLE; endcase end
endmodule
