// GENERATED by csc.py -- self-checking testbench (checker = the constraint).
module tb_top;
  logic clk=0, rst_n=0, req=0, v; logic [11:0] s;
  localparam int N=200000;
  csc_sampler dut(.clk,.rst_n,.req,.valid(v),.sample_o(s));
  always #5 clk=~clk;
  function automatic bit legal(input logic [11:0] sample);
    automatic logic [7:0] addr = sample[7:0];
    automatic logic [0:0] kind = sample[8:8];
    automatic logic [2:0] prio = sample[11:9];
    legal = ((addr[1:0] == 0)) && (((!((kind == 1))) || ((addr[7] == 0)))) && ((prio != 0)) && (((!((kind == 0))) || ((prio <= 3))));
  endfunction
  integer i, n=0, bad=0; bit seen [int];
  initial begin
    rst_n=0; repeat(3)@(posedge clk); rst_n=1; @(posedge clk); req=1;
    while(n<N) begin @(posedge clk); if(v) begin
      n++; if(!legal(s)) bad++; seen[s]=1; end end
    $display("checked=%0d illegal=%0d distinct=%0d / nsol=416", n, bad, seen.size());
    if(bad==0 && seen.size()==416)
      $display(">>> csc: all legal AND full coverage (416 solutions)");
    $finish;
  end
endmodule
