// GENERATED by csc.py -- unrank as a package function (for ConstraintActor).
package spec_proto_pkg;
  localparam logic [15:0] NSOL = 16'd416;
  localparam logic [15:0] SEED = 16'hACE1, TAPS = 16'hB400;
  localparam logic [4:0] ROOT = 5'd31;
  function automatic logic [4:0] f_lo(input logic [4:0] i);
    logic [4:0] r; case(i)
      5'd0: r = 5'd0;
      5'd1: r = 5'd1;
      5'd2: r = 5'd0;
      5'd3: r = 5'd1;
      5'd4: r = 5'd2;
      5'd5: r = 5'd3;
      5'd6: r = 5'd4;
      5'd7: r = 5'd0;
      5'd8: r = 5'd1;
      5'd9: r = 5'd7;
      5'd10: r = 5'd8;
      5'd11: r = 5'd9;
      5'd12: r = 5'd6;
      5'd13: r = 5'd2;
      5'd14: r = 5'd13;
      5'd15: r = 5'd6;
      5'd16: r = 5'd12;
      5'd17: r = 5'd16;
      5'd18: r = 5'd17;
      5'd19: r = 5'd18;
      5'd20: r = 5'd19;
      5'd21: r = 5'd20;
      5'd22: r = 5'd14;
      5'd23: r = 5'd22;
      5'd24: r = 5'd23;
      5'd25: r = 5'd24;
      5'd26: r = 5'd25;
      5'd27: r = 5'd26;
      5'd28: r = 5'd27;
      5'd29: r = 5'd21;
      5'd30: r = 5'd28;
      5'd31: r = 5'd29;
      default: r='0; endcase f_lo=r; endfunction
  function automatic logic [4:0] f_hi(input logic [4:0] i);
    logic [4:0] r; case(i)
      5'd0: r = 5'd0;
      5'd1: r = 5'd1;
      5'd2: r = 5'd0;
      5'd3: r = 5'd0;
      5'd4: r = 5'd3;
      5'd5: r = 5'd3;
      5'd6: r = 5'd5;
      5'd7: r = 5'd1;
      5'd8: r = 5'd1;
      5'd9: r = 5'd8;
      5'd10: r = 5'd8;
      5'd11: r = 5'd10;
      5'd12: r = 5'd11;
      5'd13: r = 5'd2;
      5'd14: r = 5'd13;
      5'd15: r = 5'd14;
      5'd16: r = 5'd15;
      5'd17: r = 5'd16;
      5'd18: r = 5'd17;
      5'd19: r = 5'd18;
      5'd20: r = 5'd19;
      5'd21: r = 5'd20;
      5'd22: r = 5'd14;
      5'd23: r = 5'd22;
      5'd24: r = 5'd23;
      5'd25: r = 5'd24;
      5'd26: r = 5'd25;
      5'd27: r = 5'd26;
      5'd28: r = 5'd27;
      5'd29: r = 5'd28;
      5'd30: r = 5'd28;
      5'd31: r = 5'd30;
      default: r='0; endcase f_hi=r; endfunction
  function automatic logic [15:0] f_clo(input logic [4:0] i);
    logic [15:0] r; case(i)
      5'd0: r = 16'd0;
      5'd1: r = 16'd1;
      5'd2: r = 16'd0;
      5'd3: r = 16'd1;
      5'd4: r = 16'd0;
      5'd5: r = 16'd1;
      5'd6: r = 16'd1;
      5'd7: r = 16'd0;
      5'd8: r = 16'd1;
      5'd9: r = 16'd1;
      5'd10: r = 16'd2;
      5'd11: r = 16'd3;
      5'd12: r = 16'd3;
      5'd13: r = 16'd0;
      5'd14: r = 16'd0;
      5'd15: r = 16'd3;
      5'd16: r = 16'd10;
      5'd17: r = 16'd13;
      5'd18: r = 16'd26;
      5'd19: r = 16'd52;
      5'd20: r = 16'd104;
      5'd21: r = 16'd208;
      5'd22: r = 16'd0;
      5'd23: r = 16'd0;
      5'd24: r = 16'd0;
      5'd25: r = 16'd0;
      5'd26: r = 16'd0;
      5'd27: r = 16'd0;
      5'd28: r = 16'd0;
      5'd29: r = 16'd416;
      5'd30: r = 16'd0;
      5'd31: r = 16'd416;
      default: r='0; endcase f_clo=r; endfunction
  function automatic logic [15:0] lstep(input logic [15:0] s);
    lstep=(s>>1)^(s[0]?TAPS:16'h0); endfunction
  function automatic logic [11:0] unrank(input logic [15:0] lfsr_val);
    logic [15:0] R, clo; logic [4:0] idx; logic [11:0] acc; logic [31:0] prod;
    prod = {16'h0,lfsr_val} * {16'h0,NSOL}; R = prod[31:16];  // Lemire range reduction
    idx = ROOT; acc = '0;
    for (int lvl=0; lvl<12; lvl++) begin
      clo = f_clo(idx);
      if (R < clo) begin acc[lvl] = 1'b0; idx = f_lo(idx); end
      else         begin acc[lvl] = 1'b1; R = R - clo; idx = f_hi(idx); end
    end
    return acc;
  endfunction
endpackage
