// GENERATED by csc.py -- self-checking testbench (checker = the constraint).
module tb_top;
  logic clk=0, rst_n=0, req=0, v; logic [9:0] s;
  localparam int N=200000;
  csc_sampler dut(.clk,.rst_n,.req,.valid(v),.sample_o(s));
  always #5 clk=~clk;
  function automatic bit legal(input logic [9:0] sample);
    automatic logic [1:0] size = sample[1:0];
    automatic logic [1:0] burst = sample[3:2];
    automatic logic [3:0] len = sample[7:4];
    automatic logic [1:0] region = sample[9:8];
    legal = ((burst != 3)) && (((!((burst == 0))) || ((len <= 3)))) && (((!((burst == 2))) || (((len)==1 || (len)==3 || (len)==7 || (len)==15)))) && ((size <= 3)) && ((region != 0));
  endfunction
  integer i, n=0, bad=0; bit seen [int];
  initial begin
    rst_n=0; repeat(3)@(posedge clk); rst_n=1; @(posedge clk); req=1;
    while(n<N) begin @(posedge clk); if(v) begin
      n++; if(!legal(s)) bad++; seen[s]=1; end end
    $display("checked=%0d illegal=%0d distinct=%0d / nsol=288", n, bad, seen.size());
    if(bad==0 && seen.size()==288)
      $display(">>> csc: all legal AND full coverage (288 solutions)");
    $finish;
  end
endmodule
