// GENERATED by csc.py -- WEIGHTED (dist) sampler: cumulative-weight select.
module csc_sampler (input logic clk, rst_n, req, output logic valid,
  output logic [0:0] sample_o);
  localparam logic [31:0] TOTAL = 32'd100;
  localparam logic [15:0] SEED = 16'hACE1, TAPS = 16'hB400;
  function automatic logic [15:0] lstep(input logic [15:0] s);
    lstep = (s>>1) ^ (s[0]?TAPS:16'h0); endfunction
  logic [15:0] lfsr; logic [31:0] R; logic [0:0] out;
  logic [47:0] prod; assign prod = {32'h0, lfsr} * {16'h0, TOTAL};
  assign R = prod[47:16];                                // Lemire range reduction
  always_comb begin out = 1'd0;
      if (R >= 32'd70) out = 1'd1;
  end
  always_ff @(posedge clk or negedge rst_n) if(!rst_n) begin
      lfsr<=SEED; valid<=0; sample_o<='0;
    end else begin valid<=0;
      if(req) begin sample_o<=out; valid<=1; lfsr<=lstep(lfsr); end end
endmodule
