// GENERATED by csc.py -- self-checking testbench (checker = the constraint).
module tb_top;
  logic clk=0, rst_n=0, req=0, v; logic [14:0] s;
  localparam int N=200000;
  csc_sampler dut(.clk,.rst_n,.req,.valid(v),.sample_o(s));
  always #5 clk=~clk;
  function automatic bit legal(input logic [14:0] sample);
    automatic logic [4:0] regs__0 = sample[4:0];
    automatic logic [4:0] regs__1 = sample[9:5];
    automatic logic [4:0] regs__2 = sample[14:10];
    legal = ((((1 && (1 && (regs__0 != 0))) && (1 && (regs__1 != 0))) && (1 && (regs__2 != 0)))) && ((((1 && (regs__0 != regs__1)) && (regs__0 != regs__2)) && (regs__1 != regs__2)));
  endfunction
  integer i, n=0, bad=0; bit seen [int];
  initial begin
    rst_n=0; repeat(3)@(posedge clk); rst_n=1; @(posedge clk); req=1;
    while(n<N) begin @(posedge clk); if(v) begin
      n++; if(!legal(s)) bad++; seen[s]=1; end end
    $display("checked=%0d illegal=%0d distinct=%0d / nsol=26970", n, bad, seen.size());
    if(bad==0 && seen.size()==26970)
      $display(">>> csc: all legal AND full coverage (26970 solutions)");
    $finish;
  end
endmodule
