// GENERATED by csc.py -- self-checking testbench (checker = the constraint).
module tb_top;
  logic clk=0, rst_n=0, req=0, v; logic [12:0] s;
  localparam int N=200000;
  csc_sampler dut(.clk,.rst_n,.req,.valid(v),.sample_o(s));
  always #5 clk=~clk;
  function automatic bit legal(input logic [12:0] sample);
    automatic logic [4:0] rd = sample[4:0];
    automatic logic [4:0] rs1 = sample[9:5];
    automatic logic [2:0] funct = sample[12:10];
    legal = ((rd != 0)) && ((rs1 != rd)) && (((funct)==0 || (funct)==1 || (funct)==2 || (funct)==5));
  endfunction
  integer i, n=0, bad=0; bit seen [int];
  initial begin
    rst_n=0; repeat(3)@(posedge clk); rst_n=1; @(posedge clk); req=1;
    while(n<N) begin @(posedge clk); if(v) begin
      n++; if(!legal(s)) bad++; seen[s]=1; end end
    $display("checked=%0d illegal=%0d distinct=%0d / nsol=3844", n, bad, seen.size());
    if(bad==0 && seen.size()==3844)
      $display(">>> csc: all legal AND full coverage (3844 solutions)");
    $finish;
  end
endmodule
