// GENERATED by csc.py -- self-checking testbench (checker = the constraint).
module tb_top;
  logic clk=0, rst_n=0, req=0, v; logic [14:0] s;
  localparam int N=200000;
  csc_sampler dut(.clk,.rst_n,.req,.valid(v),.sample_o(s));
  always #5 clk=~clk;
  function automatic bit legal(input logic [14:0] sample);
    automatic logic [4:0] avail__0 = sample[4:0];
    automatic logic [4:0] avail__1 = sample[9:5];
    automatic logic [4:0] avail__2 = sample[14:10];
    legal = ((((1 && (1 && (!((avail__0)==0 || (avail__0)==2 || (avail__0)==3 || (avail__0)==4)))) && (1 && (!((avail__1)==0 || (avail__1)==2 || (avail__1)==3 || (avail__1)==4)))) && (1 && (!((avail__2)==0 || (avail__2)==2 || (avail__2)==3 || (avail__2)==4))))) && ((((1 && (avail__0 != avail__1)) && (avail__0 != avail__2)) && (avail__1 != avail__2)));
  endfunction
  integer i, n=0, bad=0; bit seen [int];
  initial begin
    rst_n=0; repeat(3)@(posedge clk); rst_n=1; @(posedge clk); req=1;
    while(n<N) begin @(posedge clk); if(v) begin
      n++; if(!legal(s)) bad++; seen[s]=1; end end
    $display("checked=%0d illegal=%0d distinct=%0d / nsol=19656", n, bad, seen.size());
    if(bad==0 && seen.size()==19656)
      $display(">>> csc: all legal AND full coverage (19656 solutions)");
    $finish;
  end
endmodule
