// GENERATED by csc.py -- WEIGHTED (dist) sampler: cumulative-weight select.
module csc_sampler (input logic clk, rst_n, req, output logic valid,
  output logic [4:0] sample_o);
  localparam logic [31:0] TOTAL = 32'd750;
  localparam logic [15:0] SEED = 16'hACE1, TAPS = 16'hB400;
  function automatic logic [15:0] lstep(input logic [15:0] s);
    lstep = (s>>1) ^ (s[0]?TAPS:16'h0); endfunction
  logic [15:0] lfsr; logic [31:0] R; logic [4:0] out;
  logic [25:0] prod; assign prod = 26'(lfsr) * 26'(TOTAL);
  assign R = 32'(prod[25:16]);                       // Lemire range reduction (sized)
  always_comb begin out = 5'd1;
      if (R >= 32'd375) out = 5'd2;
      if (R >= 32'd400) out = 5'd3;
      if (R >= 32'd425) out = 5'd4;
      if (R >= 32'd450) out = 5'd5;
      if (R >= 32'd600) out = 5'd7;
      if (R >= 32'd606) out = 5'd8;
      if (R >= 32'd612) out = 5'd9;
      if (R >= 32'd618) out = 5'd10;
      if (R >= 32'd624) out = 5'd11;
      if (R >= 32'd630) out = 5'd12;
      if (R >= 32'd636) out = 5'd13;
      if (R >= 32'd642) out = 5'd14;
      if (R >= 32'd648) out = 5'd15;
      if (R >= 32'd654) out = 5'd16;
      if (R >= 32'd660) out = 5'd17;
      if (R >= 32'd666) out = 5'd18;
      if (R >= 32'd672) out = 5'd19;
      if (R >= 32'd678) out = 5'd20;
      if (R >= 32'd684) out = 5'd21;
      if (R >= 32'd690) out = 5'd22;
      if (R >= 32'd696) out = 5'd23;
      if (R >= 32'd702) out = 5'd24;
      if (R >= 32'd708) out = 5'd25;
      if (R >= 32'd714) out = 5'd26;
      if (R >= 32'd720) out = 5'd27;
      if (R >= 32'd726) out = 5'd28;
      if (R >= 32'd732) out = 5'd29;
      if (R >= 32'd738) out = 5'd30;
      if (R >= 32'd744) out = 5'd31;
  end
  always_ff @(posedge clk or negedge rst_n) if(!rst_n) begin
      lfsr<=SEED; valid<=0; sample_o<='0;
    end else begin valid<=0;
      if(req) begin sample_o<=out; valid<=1; lfsr<=lstep(lfsr); end end
endmodule
