// GENERATED by csc.py -- self-checking testbench (checker = the constraint).
module tb_top;
  logic clk=0, rst_n=0, req=0, v; logic [15:0] s;
  localparam int N=200000;
  csc_sampler dut(.clk,.rst_n,.req,.valid(v),.sample_o(s));
  always #5 clk=~clk;
  function automatic bit legal(input logic [15:0] sample);
    automatic logic [4:0] vd = sample[4:0];
    automatic logic [4:0] vs1 = sample[9:5];
    automatic logic [4:0] vs2 = sample[14:10];
    automatic logic [0:0] vm = sample[15:15];
    legal = ((vd != vs2)) && ((vd != vs1)) && (((!((vm == 0))) || ((vd != 0))));
  endfunction
  integer i, n=0, bad=0; bit seen [int];
  initial begin
    rst_n=0; repeat(3)@(posedge clk); rst_n=1; @(posedge clk); req=1;
    while(n<N) begin @(posedge clk); if(v) begin
      n++; if(!legal(s)) bad++; seen[s]=1; end end
    $display("checked=%0d illegal=%0d distinct=%0d / nsol=60543", n, bad, seen.size());
    if(bad==0 && seen.size()==60543)
      $display(">>> csc: all legal AND full coverage (60543 solutions)");
    $finish;
  end
endmodule
