// Auto-generated by appC_earlgrey/tools/reggen_actor.py
// Source: rv_timer.hjson
// DO NOT EDIT: regenerate with `reggen_actor.py rv_timer.hjson`

package rv_timer_ral_defs_pkg;
  import actor_ral_pkg::*;

  function void define_rv_timer_ral(RalActor ral);
    ral.define_reg("CFG0", 32'h00000100, RAL_RW, 32'h00000000);
    ral.define_field("CFG0", "prescale", 0, 12, RAL_RW, 32'h0);
    ral.define_field("CFG0", "step", 16, 8, RAL_RW, 32'h1);
    ral.define_reg("TIMER_V_LOWER0", 32'h00000104, RAL_RW, 32'h00000000);
    ral.define_field("TIMER_V_LOWER0", "v", 0, 32, RAL_RW, 32'h0);
    ral.define_reg("TIMER_V_UPPER0", 32'h00000108, RAL_RW, 32'h00000000);
    ral.define_field("TIMER_V_UPPER0", "v", 0, 32, RAL_RW, 32'h0);
    ral.define_reg("COMPARE_LOWER0_0", 32'h0000010C, RAL_RW, 32'h00000000);
    ral.define_field("COMPARE_LOWER0_0", "v", 0, 32, RAL_RW, 32'hFFFFFFFF);
    ral.define_reg("COMPARE_UPPER0_0", 32'h00000110, RAL_RW, 32'h00000000);
    ral.define_field("COMPARE_UPPER0_0", "v", 0, 32, RAL_RW, 32'hFFFFFFFF);
  endfunction
endpackage
