// Auto-generated by appC_earlgrey/tools/reggen_actor.py
// Source: hmac.hjson
// DO NOT EDIT: regenerate with `reggen_actor.py hmac.hjson`

package hmac_ral_defs_pkg;
  import actor_ral_pkg::*;

  function void define_hmac_ral(RalActor ral);
    ral.define_reg("INTR_STATE", 32'h00000000, RAL_W1C, 32'h00000000);
    ral.define_field("INTR_STATE", "hmac_done", 0, 1, RAL_RW, 32'h0);
    ral.define_field("INTR_STATE", "fifo_empty", 1, 1, RAL_RW, 32'h0);
    ral.define_field("INTR_STATE", "hmac_err", 2, 1, RAL_RW, 32'h0);
    ral.define_reg("INTR_ENABLE", 32'h00000004, RAL_RW, 32'h00000000);
    ral.define_field("INTR_ENABLE", "hmac_done", 0, 1, RAL_RW, 32'h0);
    ral.define_field("INTR_ENABLE", "fifo_empty", 1, 1, RAL_RW, 32'h0);
    ral.define_field("INTR_ENABLE", "hmac_err", 2, 1, RAL_RW, 32'h0);
    ral.define_reg("INTR_TEST", 32'h00000008, RAL_WO, 32'h00000000);
    ral.define_field("INTR_TEST", "hmac_done", 0, 1, RAL_WO, 32'h0);
    ral.define_field("INTR_TEST", "fifo_empty", 1, 1, RAL_WO, 32'h0);
    ral.define_field("INTR_TEST", "hmac_err", 2, 1, RAL_WO, 32'h0);
    ral.define_reg("ALERT_TEST", 32'h0000000C, RAL_WO, 32'h00000000);
    ral.define_field("ALERT_TEST", "fatal_fault", 0, 1, RAL_WO, 32'h0);
    ral.define_reg("CFG", 32'h00000010, RAL_RW, 32'h00000000);
    ral.define_field("CFG", "hmac_en", 0, 1, RAL_RW, 32'h0);
    ral.define_field("CFG", "sha_en", 1, 1, RAL_RW, 32'h0);
    ral.define_field("CFG", "endian_swap", 2, 1, RAL_RW, 32'h0);
    ral.define_field("CFG", "digest_swap", 3, 1, RAL_RW, 32'h0);
    ral.define_field("CFG", "key_swap", 4, 1, RAL_RW, 32'h0);
    ral.define_field("CFG", "digest_size", 5, 4, RAL_RW, 32'h8);
    ral.define_field("CFG", "key_length", 9, 6, RAL_RW, 32'h20);
    ral.define_reg("CMD", 32'h00000014, RAL_W1C, 32'h00000000);
    ral.define_field("CMD", "hash_start", 0, 1, RAL_W1C, 32'h0);
    ral.define_field("CMD", "hash_process", 1, 1, RAL_W1C, 32'h0);
    ral.define_field("CMD", "hash_stop", 2, 1, RAL_W1C, 32'h0);
    ral.define_field("CMD", "hash_continue", 3, 1, RAL_W1C, 32'h0);
    ral.define_reg("STATUS", 32'h00000018, RAL_RO, 32'h00000000);
    ral.define_field("STATUS", "hmac_idle", 0, 1, RAL_RO, 32'h1);
    ral.define_field("STATUS", "fifo_empty", 1, 1, RAL_RO, 32'h1);
    ral.define_field("STATUS", "fifo_full", 2, 1, RAL_RO, 32'h0);
    ral.define_field("STATUS", "fifo_depth", 4, 6, RAL_RO, 32'h0);
    ral.define_reg("ERR_CODE", 32'h0000001C, RAL_RO, 32'h00000000);
    ral.define_field("ERR_CODE", "err_code", 0, 32, RAL_RO, 32'h0);
    ral.define_reg("WIPE_SECRET", 32'h00000020, RAL_WO, 32'h00000000);
    ral.define_field("WIPE_SECRET", "secret", 0, 32, RAL_WO, 32'h0);
    ral.define_reg("MSG_LENGTH_LOWER", 32'h00000024, RAL_RW, 32'h00000000);
    ral.define_field("MSG_LENGTH_LOWER", "v", 0, 32, RAL_RW, 32'h0);
    ral.define_reg("MSG_LENGTH_UPPER", 32'h00000028, RAL_RW, 32'h00000000);
    ral.define_field("MSG_LENGTH_UPPER", "v", 0, 32, RAL_RW, 32'h0);
  endfunction
endpackage
