// Auto-generated by appC_earlgrey/tools/reggen_actor.py
// Source: uart.hjson
// DO NOT EDIT: regenerate with `reggen_actor.py uart.hjson`

package uart_ral_defs_pkg;
  import actor_ral_pkg::*;

  function void define_uart_ral(RalActor ral);
    ral.define_reg("INTR_STATE", 32'h00000000, RAL_W1C, 32'h00000000);
    ral.define_field("INTR_STATE", "tx_watermark", 0, 1, RAL_RW, 32'h1);
    ral.define_field("INTR_STATE", "rx_watermark", 1, 1, RAL_RW, 32'h0);
    ral.define_field("INTR_STATE", "tx_done", 2, 1, RAL_RW, 32'h0);
    ral.define_field("INTR_STATE", "rx_overflow", 3, 1, RAL_RW, 32'h0);
    ral.define_field("INTR_STATE", "rx_frame_err", 4, 1, RAL_RW, 32'h0);
    ral.define_field("INTR_STATE", "rx_break_err", 5, 1, RAL_RW, 32'h0);
    ral.define_field("INTR_STATE", "rx_timeout", 6, 1, RAL_RW, 32'h0);
    ral.define_field("INTR_STATE", "rx_parity_err", 7, 1, RAL_RW, 32'h0);
    ral.define_field("INTR_STATE", "tx_empty", 8, 1, RAL_RW, 32'h1);
    ral.define_reg("INTR_ENABLE", 32'h00000004, RAL_RW, 32'h00000000);
    ral.define_field("INTR_ENABLE", "tx_watermark", 0, 1, RAL_RW, 32'h1);
    ral.define_field("INTR_ENABLE", "rx_watermark", 1, 1, RAL_RW, 32'h0);
    ral.define_field("INTR_ENABLE", "tx_done", 2, 1, RAL_RW, 32'h0);
    ral.define_field("INTR_ENABLE", "rx_overflow", 3, 1, RAL_RW, 32'h0);
    ral.define_field("INTR_ENABLE", "rx_frame_err", 4, 1, RAL_RW, 32'h0);
    ral.define_field("INTR_ENABLE", "rx_break_err", 5, 1, RAL_RW, 32'h0);
    ral.define_field("INTR_ENABLE", "rx_timeout", 6, 1, RAL_RW, 32'h0);
    ral.define_field("INTR_ENABLE", "rx_parity_err", 7, 1, RAL_RW, 32'h0);
    ral.define_field("INTR_ENABLE", "tx_empty", 8, 1, RAL_RW, 32'h1);
    ral.define_reg("INTR_TEST", 32'h00000008, RAL_WO, 32'h00000000);
    ral.define_field("INTR_TEST", "tx_watermark", 0, 1, RAL_WO, 32'h1);
    ral.define_field("INTR_TEST", "rx_watermark", 1, 1, RAL_WO, 32'h0);
    ral.define_field("INTR_TEST", "tx_done", 2, 1, RAL_WO, 32'h0);
    ral.define_field("INTR_TEST", "rx_overflow", 3, 1, RAL_WO, 32'h0);
    ral.define_field("INTR_TEST", "rx_frame_err", 4, 1, RAL_WO, 32'h0);
    ral.define_field("INTR_TEST", "rx_break_err", 5, 1, RAL_WO, 32'h0);
    ral.define_field("INTR_TEST", "rx_timeout", 6, 1, RAL_WO, 32'h0);
    ral.define_field("INTR_TEST", "rx_parity_err", 7, 1, RAL_WO, 32'h0);
    ral.define_field("INTR_TEST", "tx_empty", 8, 1, RAL_WO, 32'h1);
    ral.define_reg("ALERT_TEST", 32'h0000000C, RAL_WO, 32'h00000000);
    ral.define_field("ALERT_TEST", "fatal_fault", 0, 1, RAL_WO, 32'h0);
    ral.define_reg("CTRL", 32'h00000010, RAL_RW, 32'h00000000);
    ral.define_field("CTRL", "TX", 0, 1, RAL_RW, 32'h0);
    ral.define_field("CTRL", "RX", 1, 1, RAL_RW, 32'h0);
    ral.define_field("CTRL", "NF", 2, 1, RAL_RW, 32'h0);
    ral.define_field("CTRL", "SLPBK", 4, 1, RAL_RW, 32'h0);
    ral.define_field("CTRL", "LLPBK", 5, 1, RAL_RW, 32'h0);
    ral.define_field("CTRL", "PARITY_EN", 6, 1, RAL_RW, 32'h0);
    ral.define_field("CTRL", "PARITY_ODD", 7, 1, RAL_RW, 32'h0);
    ral.define_field("CTRL", "RXBLVL", 8, 2, RAL_RW, 32'h0);
    ral.define_field("CTRL", "NCO", 16, 16, RAL_RW, 32'h0);
    ral.define_reg("STATUS", 32'h00000014, RAL_RO, 32'h00000000);
    ral.define_field("STATUS", "TXFULL", 0, 1, RAL_RO, 32'h0);
    ral.define_field("STATUS", "RXFULL", 1, 1, RAL_RO, 32'h0);
    ral.define_field("STATUS", "TXEMPTY", 2, 1, RAL_RO, 32'h1);
    ral.define_field("STATUS", "TXIDLE", 3, 1, RAL_RO, 32'h1);
    ral.define_field("STATUS", "RXIDLE", 4, 1, RAL_RO, 32'h1);
    ral.define_field("STATUS", "RXEMPTY", 5, 1, RAL_RO, 32'h1);
    ral.define_reg("RDATA", 32'h00000018, RAL_RO, 32'h00000000);
    ral.define_reg("WDATA", 32'h0000001C, RAL_WO, 32'h00000000);
    ral.define_reg("FIFO_CTRL", 32'h00000020, RAL_RW, 32'h00000000);
    ral.define_field("FIFO_CTRL", "RXRST", 0, 1, RAL_WO, 32'h0);
    ral.define_field("FIFO_CTRL", "TXRST", 1, 1, RAL_WO, 32'h0);
    ral.define_field("FIFO_CTRL", "RXILVL", 2, 3, RAL_RW, 32'h0);
    ral.define_field("FIFO_CTRL", "TXILVL", 5, 3, RAL_RW, 32'h0);
    ral.define_reg("FIFO_STATUS", 32'h00000024, RAL_RO, 32'h00000000);
    ral.define_field("FIFO_STATUS", "TXLVL", 0, 8, RAL_RO, 32'h0);
    ral.define_field("FIFO_STATUS", "RXLVL", 16, 8, RAL_RO, 32'h0);
    ral.define_reg("OVRD", 32'h00000028, RAL_RW, 32'h00000000);
    ral.define_field("OVRD", "TXEN", 0, 1, RAL_RW, 32'h0);
    ral.define_field("OVRD", "TXVAL", 1, 1, RAL_RW, 32'h0);
    ral.define_reg("VAL", 32'h0000002C, RAL_RO, 32'h00000000);
    ral.define_field("VAL", "RX", 0, 16, RAL_RO, 32'h0);
    ral.define_reg("TIMEOUT_CTRL", 32'h00000030, RAL_RW, 32'h00000000);
    ral.define_field("TIMEOUT_CTRL", "VAL", 0, 24, RAL_RW, 32'h0);
    ral.define_field("TIMEOUT_CTRL", "EN", 31, 1, RAL_RW, 32'h0);
  endfunction
endpackage
