// Auto-generated by appC_earlgrey/tools/reggen_actor.py
// Source: gpio.hjson
// DO NOT EDIT: regenerate with `reggen_actor.py gpio.hjson`

package gpio_ral_defs_pkg;
  import actor_ral_pkg::*;

  function void define_gpio_ral(RalActor ral);
    ral.define_reg("INTR_STATE", 32'h00000000, RAL_W1C, 32'h00000000);
    ral.define_field("INTR_STATE", "gpio", 0, 1, RAL_RW, 32'h0);
    ral.define_reg("INTR_ENABLE", 32'h00000004, RAL_RW, 32'h00000000);
    ral.define_field("INTR_ENABLE", "gpio", 0, 1, RAL_RW, 32'h0);
    ral.define_reg("INTR_TEST", 32'h00000008, RAL_WO, 32'h00000000);
    ral.define_field("INTR_TEST", "gpio", 0, 1, RAL_WO, 32'h0);
    ral.define_reg("ALERT_TEST", 32'h0000000C, RAL_WO, 32'h00000000);
    ral.define_field("ALERT_TEST", "fatal_fault", 0, 1, RAL_WO, 32'h0);
    ral.define_reg("DATA_IN", 32'h00000010, RAL_RO, 32'h00000000);
    ral.define_reg("DIRECT_OUT", 32'h00000014, RAL_RW, 32'h00000000);
    ral.define_reg("MASKED_OUT_LOWER", 32'h00000018, RAL_RW, 32'h00000000);
    ral.define_field("MASKED_OUT_LOWER", "data", 0, 16, RAL_RW, 32'h0);
    ral.define_field("MASKED_OUT_LOWER", "mask", 16, 16, RAL_WO, 32'h0);
    ral.define_reg("MASKED_OUT_UPPER", 32'h0000001C, RAL_RW, 32'h00000000);
    ral.define_field("MASKED_OUT_UPPER", "data", 0, 16, RAL_RW, 32'h0);
    ral.define_field("MASKED_OUT_UPPER", "mask", 16, 16, RAL_WO, 32'h0);
    ral.define_reg("DIRECT_OE", 32'h00000020, RAL_RW, 32'h00000000);
    ral.define_reg("MASKED_OE_LOWER", 32'h00000024, RAL_RW, 32'h00000000);
    ral.define_field("MASKED_OE_LOWER", "data", 0, 16, RAL_RW, 32'h0);
    ral.define_field("MASKED_OE_LOWER", "mask", 16, 16, RAL_RW, 32'h0);
    ral.define_reg("MASKED_OE_UPPER", 32'h00000028, RAL_RW, 32'h00000000);
    ral.define_field("MASKED_OE_UPPER", "data", 0, 16, RAL_RW, 32'h0);
    ral.define_field("MASKED_OE_UPPER", "mask", 16, 16, RAL_RW, 32'h0);
    ral.define_reg("INTR_CTRL_EN_RISING", 32'h0000002C, RAL_RW, 32'h00000000);
    ral.define_reg("INTR_CTRL_EN_FALLING", 32'h00000030, RAL_RW, 32'h00000000);
    ral.define_reg("INTR_CTRL_EN_LVLHIGH", 32'h00000034, RAL_RW, 32'h00000000);
    ral.define_reg("INTR_CTRL_EN_LVLLOW", 32'h00000038, RAL_RW, 32'h00000000);
    ral.define_reg("CTRL_EN_INPUT_FILTER", 32'h0000003C, RAL_RW, 32'h00000000);
    ral.define_reg("HW_STRAPS_DATA_IN_VALID", 32'h00000040, RAL_RO, 32'h00000000);
    ral.define_reg("HW_STRAPS_DATA_IN", 32'h00000044, RAL_RO, 32'h00000000);
  endfunction
endpackage
