// GENERATED by build_bdd.py -- do not edit.  Tier-1 BDD UNRANK sampler.
// One uniform R in [0,416) decodes into the R-th satisfying assignment of the
// compiled constraint: zero rejection, fixed 12-step latency, provably uniform.
// ROM is case() functions (Verilator- and yosys-frontend-clean).
module bdd_constraint_sampler (
  input  logic            clk,
  input  logic            rst_n,
  input  logic            req,
  output logic            valid,
  output logic [11:0] sample_o    // bit i = variable i (addr[7:0],kind,prio[2:0])
);
  localparam logic [15:0] NSOL = 16'd416;
  localparam logic [15:0] SEED = 16'hACE1;
  localparam logic [15:0] TAPS = 16'hB400;
  localparam logic [4:0]  ROOT = 5'd29;

  function automatic logic [4:0] f_lo(input logic [4:0] i);
    logic [4:0] r; case (i)
      5'd0: r = 5'd0;
      5'd1: r = 5'd1;
      5'd2: r = 5'd0;
      5'd3: r = 5'd2;
      5'd4: r = 5'd3;
      5'd5: r = 5'd4;
      5'd6: r = 5'd5;
      5'd7: r = 5'd1;
      5'd8: r = 5'd7;
      5'd9: r = 5'd8;
      5'd10: r = 5'd9;
      5'd11: r = 5'd10;
      5'd12: r = 5'd6;
      5'd13: r = 5'd11;
      5'd14: r = 5'd12;
      5'd15: r = 5'd6;
      5'd16: r = 5'd15;
      5'd17: r = 5'd14;
      5'd18: r = 5'd17;
      5'd19: r = 5'd16;
      5'd20: r = 5'd19;
      5'd21: r = 5'd18;
      5'd22: r = 5'd20;
      5'd23: r = 5'd21;
      5'd24: r = 5'd13;
      5'd25: r = 5'd14;
      5'd26: r = 5'd25;
      5'd27: r = 5'd26;
      5'd28: r = 5'd27;
      5'd29: r = 5'd23;
      default: r = '0; endcase f_lo = r;
  endfunction
  function automatic logic [4:0] f_hi(input logic [4:0] i);
    logic [4:0] r; case (i)
      5'd0: r = 5'd0;
      5'd1: r = 5'd1;
      5'd2: r = 5'd0;
      5'd3: r = 5'd2;
      5'd4: r = 5'd3;
      5'd5: r = 5'd4;
      5'd6: r = 5'd5;
      5'd7: r = 5'd1;
      5'd8: r = 5'd7;
      5'd9: r = 5'd8;
      5'd10: r = 5'd9;
      5'd11: r = 5'd10;
      5'd12: r = 5'd11;
      5'd13: r = 5'd11;
      5'd14: r = 5'd13;
      5'd15: r = 5'd6;
      5'd16: r = 5'd15;
      5'd17: r = 5'd16;
      5'd18: r = 5'd17;
      5'd19: r = 5'd16;
      5'd20: r = 5'd19;
      5'd21: r = 5'd20;
      5'd22: r = 5'd20;
      5'd23: r = 5'd22;
      5'd24: r = 5'd13;
      5'd25: r = 5'd24;
      5'd26: r = 5'd19;
      5'd27: r = 5'd20;
      5'd28: r = 5'd22;
      5'd29: r = 5'd28;
      default: r = '0; endcase f_hi = r;
  endfunction
  function automatic logic [15:0] f_clo(input logic [4:0] i);  // count(lo child)
    logic [15:0] r; case (i)
      5'd0: r = 16'd0;
      5'd1: r = 16'd1;
      5'd2: r = 16'd0;
      5'd3: r = 16'd0;
      5'd4: r = 16'd0;
      5'd5: r = 16'd0;
      5'd6: r = 16'd0;
      5'd7: r = 16'd1;
      5'd8: r = 16'd2;
      5'd9: r = 16'd4;
      5'd10: r = 16'd8;
      5'd11: r = 16'd16;
      5'd12: r = 16'd0;
      5'd13: r = 16'd32;
      5'd14: r = 16'd32;
      5'd15: r = 16'd0;
      5'd16: r = 16'd0;
      5'd17: r = 16'd96;
      5'd18: r = 16'd96;
      5'd19: r = 16'd0;
      5'd20: r = 16'd0;
      5'd21: r = 16'd192;
      5'd22: r = 16'd0;
      5'd23: r = 16'd192;
      5'd24: r = 16'd64;
      5'd25: r = 16'd96;
      5'd26: r = 16'd224;
      5'd27: r = 16'd224;
      5'd28: r = 16'd224;
      5'd29: r = 16'd192;
      default: r = '0; endcase f_clo = r;
  endfunction
  function automatic logic [3:0] f_ord(input logic [3:0] lvl);
    logic [3:0] r; case (lvl)
      4'd0: r = 4'd8;
      4'd1: r = 4'd0;
      4'd2: r = 4'd1;
      4'd3: r = 4'd7;
      4'd4: r = 4'd11;
      4'd5: r = 4'd9;
      4'd6: r = 4'd10;
      4'd7: r = 4'd2;
      4'd8: r = 4'd3;
      4'd9: r = 4'd4;
      4'd10: r = 4'd5;
      4'd11: r = 4'd6;
      default: r = '0; endcase f_ord = r;
  endfunction

  typedef enum logic [1:0] {S_IDLE, S_WALK, S_EMIT} st_e;
  st_e             state;
  logic [15:0]     lfsr;
  logic [4:0]  idx;
  logic [15:0]     R;
  logic [4:0]      level;
  logic [11:0] acc;

  function automatic logic [15:0] lfsr_step(input logic [15:0] s);
    lfsr_step = (s >> 1) ^ (s[0] ? TAPS : 16'h0);
  endfunction

  logic [15:0] clo_c; logic bit_c;
  assign clo_c = f_clo(idx);
  assign bit_c = (R >= clo_c);          // 0 -> low child, 1 -> high child

  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      state <= S_IDLE; lfsr <= SEED; valid <= 1'b0; sample_o <= '0;
      idx <= '0; R <= '0; level <= '0; acc <= '0;
    end else begin
      valid <= 1'b0;
      case (state)
        S_IDLE: if (req) begin
          R <= lfsr % NSOL; idx <= ROOT; level <= '0; acc <= '0; state <= S_WALK;
        end
        S_WALK: begin
          acc[f_ord(level[3:0])] <= bit_c;
          idx <= bit_c ? f_hi(idx) : f_lo(idx);
          R   <= bit_c ? (R - clo_c) : R;
          level <= level + 5'd1;
          if (level == 5'd11) state <= S_EMIT;
        end
        S_EMIT: begin
          sample_o <= acc; valid <= 1'b1; lfsr <= lfsr_step(lfsr); state <= S_IDLE;
        end
        default: state <= S_IDLE;
      endcase
    end
  end
endmodule
