#!/usr/bin/env python3
"""
Tier-1 constraint compiler: declarative Boolean/relational constraint  ->
count-annotated (quasi-reduced) BDD  ->  synthesizable UNRANK sampler.

Idea (zero rejection, fixed latency, provably uniform):
  Annotate every BDD node with the number of satisfying assignments below it.
  A uniform random integer R in [0, #solutions) decodes bijectively into the
  R-th satisfying assignment by a root->leaf walk: at each node, if R < count(lo)
  go low (bit 0), else subtract count(lo), go high (bit 1).  No search, no
  rejection -- one wide random number becomes one legal transaction.

This file builds the BDD, self-tests it against brute force, emits a reference
stream (identical LFSR+unrank to the RTL), and codegens bdd_constraint_sampler.sv
(ROM as case() functions, so both Verilator and the yosys frontend accept it).
"""

# ---- the constraint (pure Boolean/relational -- BDD's home turf) -------------
# 12-bit assignment:  addr[7:0]=bits0..7,  kind=bit8 (0=READ,1=WRITE),  prio[2:0]=bits9..11
NV = 12
def predicate(idx: int) -> bool:
    b = [(idx >> i) & 1 for i in range(NV)]
    addr0, addr1, addr7, kind = b[0], b[1], b[7], b[8]
    prio_msb = b[11]
    prioval  = b[9] + 2*b[10] + 4*b[11]
    if addr0 or addr1:           return False   # C1: 4-byte aligned
    if kind == 1 and addr7 == 1: return False   # C2: WRITE -> addr low half
    if prioval == 0:             return False   # C3: prio != 0
    if kind == 0 and prio_msb:   return False   # C4: READ  -> prio <= 3
    return True

ORDER = [8, 0, 1, 7, 11, 9, 10, 2, 3, 4, 5, 6]      # BDD level -> variable
assert sorted(ORDER) == list(range(NV))

# ---- BDD build (quasi-reduced; unique table by cofactor truth-table) ---------
nodes = [(0, 0, 0), (1, 1, 1)]      # idx 0 = FALSE(count0), 1 = TRUE(count1)
T0, T1 = 0, 1
unique = {}

def cofactors(mask: int, n: int):
    half = 1 << (n - 1)
    lo = hi = 0
    for sp in range(half):
        if (mask >> (2*sp))     & 1: lo |= (1 << sp)
        if (mask >> (2*sp + 1)) & 1: hi |= (1 << sp)
    return lo, hi

def build(level: int, mask: int) -> int:
    if level == NV:
        return T1 if (mask & 1) else T0
    key = (level, mask)
    if key in unique:
        return unique[key]
    lo_mask, hi_mask = cofactors(mask, NV - level)
    lo = build(level + 1, lo_mask)
    hi = build(level + 1, hi_mask)
    idx = len(nodes)
    nodes.append((lo, hi, nodes[lo][2] + nodes[hi][2]))
    unique[key] = idx
    return idx

root_mask = 0
for s in range(1 << NV):
    idx = sum(((s >> j) & 1) << ORDER[j] for j in range(NV))
    if predicate(idx):
        root_mask |= (1 << s)
ROOT = build(0, root_mask)
NSOL = nodes[ROOT][2]

def unrank(R: int):
    idx, assign = ROOT, [0]*NV
    for level in range(NV):
        lo, hi, _ = nodes[idx]
        clo = nodes[lo][2]
        if R < clo:
            assign[ORDER[level]] = 0; idx = lo
        else:
            assign[ORDER[level]] = 1; R -= clo; idx = hi
    assert idx == T1
    return sum(v << i for i, v in enumerate(assign))

def selftest():
    brute = [i for i in range(1 << NV) if predicate(i)]
    assert NSOL == len(brute), f"count {NSOL} != brute {len(brute)}"
    seen = set()
    for R in range(NSOL):
        idx = unrank(R)
        assert predicate(idx), f"unrank({R}) illegal"
        seen.add(idx)
    assert seen == set(brute), "unrank is not a bijection onto the solution set"
    return len(brute), len(nodes)

SEED = 0xACE1; TAPS = 0xB400
def lfsr_step(s): return (s >> 1) ^ (TAPS if (s & 1) else 0)
def stream(n):
    s = SEED; out = []
    for _ in range(n):
        out.append(unrank(s % NSOL)); s = lfsr_step(s)
    return out
def fields(idx):
    return (idx & 0xFF, (idx >> 8) & 1, (idx >> 9) & 7)

def clog2(x):
    b = 1
    while (1 << b) < x: b += 1
    return b

def emit_sv(path):
    NN = len(nodes)
    W = max(1, clog2(NN))                 # node-index width
    lo  = "\n".join(f"      {W}'d{i}: r = {W}'d{nodes[i][0]};" for i in range(NN))
    hi  = "\n".join(f"      {W}'d{i}: r = {W}'d{nodes[i][1]};" for i in range(NN))
    clo = "\n".join(f"      {W}'d{i}: r = 16'd{nodes[nodes[i][0]][2]};" for i in range(NN))
    od  = "\n".join(f"      4'd{k}: r = 4'd{ORDER[k]};" for k in range(NV))
    sv = f"""// GENERATED by build_bdd.py -- do not edit.  Tier-1 BDD UNRANK sampler.
// One uniform R in [0,{NSOL}) decodes into the R-th satisfying assignment of the
// compiled constraint: zero rejection, fixed {NV}-step latency, provably uniform.
// ROM is case() functions (Verilator- and yosys-frontend-clean).
module bdd_constraint_sampler (
  input  logic            clk,
  input  logic            rst_n,
  input  logic            req,
  output logic            valid,
  output logic [{NV-1}:0] sample_o    // bit i = variable i (addr[7:0],kind,prio[2:0])
);
  localparam logic [15:0] NSOL = 16'd{NSOL};
  localparam logic [15:0] SEED = 16'h{SEED:04X};
  localparam logic [15:0] TAPS = 16'h{TAPS:04X};
  localparam logic [{W-1}:0]  ROOT = {W}'d{ROOT};

  function automatic logic [{W-1}:0] f_lo(input logic [{W-1}:0] i);
    logic [{W-1}:0] r; case (i)
{lo}
      default: r = '0; endcase f_lo = r;
  endfunction
  function automatic logic [{W-1}:0] f_hi(input logic [{W-1}:0] i);
    logic [{W-1}:0] r; case (i)
{hi}
      default: r = '0; endcase f_hi = r;
  endfunction
  function automatic logic [15:0] f_clo(input logic [{W-1}:0] i);  // count(lo child)
    logic [15:0] r; case (i)
{clo}
      default: r = '0; endcase f_clo = r;
  endfunction
  function automatic logic [3:0] f_ord(input logic [3:0] lvl);
    logic [3:0] r; case (lvl)
{od}
      default: r = '0; endcase f_ord = r;
  endfunction

  typedef enum logic [1:0] {{S_IDLE, S_WALK, S_EMIT}} st_e;
  st_e             state;
  logic [15:0]     lfsr;
  logic [{W-1}:0]  idx;
  logic [15:0]     R;
  logic [4:0]      level;
  logic [{NV-1}:0] acc;

  function automatic logic [15:0] lfsr_step(input logic [15:0] s);
    lfsr_step = (s >> 1) ^ (s[0] ? TAPS : 16'h0);
  endfunction

  logic [15:0] clo_c; logic bit_c;
  assign clo_c = f_clo(idx);
  assign bit_c = (R >= clo_c);          // 0 -> low child, 1 -> high child

  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      state <= S_IDLE; lfsr <= SEED; valid <= 1'b0; sample_o <= '0;
      idx <= '0; R <= '0; level <= '0; acc <= '0;
    end else begin
      valid <= 1'b0;
      case (state)
        S_IDLE: if (req) begin
          R <= lfsr % NSOL; idx <= ROOT; level <= '0; acc <= '0; state <= S_WALK;
        end
        S_WALK: begin
          acc[f_ord(level[3:0])] <= bit_c;
          idx <= bit_c ? f_hi(idx) : f_lo(idx);
          R   <= bit_c ? (R - clo_c) : R;
          level <= level + 5'd1;
          if (level == 5'd{NV-1}) state <= S_EMIT;
        end
        S_EMIT: begin
          sample_o <= acc; valid <= 1'b1; lfsr <= lfsr_step(lfsr); state <= S_IDLE;
        end
        default: state <= S_IDLE;
      endcase
    end
  end
endmodule
"""
    with open(path, "w") as f:
        f.write(sv)

def emit_pkg(path):
    """Combinational unrank as a package function -- the class-based ConstraintActor
    calls this, so the sim (class) and fabric (module) renderings share one table."""
    NN = len(nodes); W = max(1, clog2(NN))
    lo  = "\n".join(f"      {W}'d{i}: r = {W}'d{nodes[i][0]};" for i in range(NN))
    hi  = "\n".join(f"      {W}'d{i}: r = {W}'d{nodes[i][1]};" for i in range(NN))
    clo = "\n".join(f"      {W}'d{i}: r = 16'd{nodes[nodes[i][0]][2]};" for i in range(NN))
    od  = "\n".join(f"      4'd{k}: r = 4'd{ORDER[k]};" for k in range(NV))
    pkg = f"""// GENERATED by build_bdd.py.  Unrank as package functions (shared by the
// class-based ConstraintActor in sim and, structurally, the RTL module on fabric).
package bdd_unrank_pkg;
  localparam logic [15:0] NSOL = 16'd{NSOL};
  localparam logic [15:0] SEED = 16'h{SEED:04X};
  localparam logic [15:0] TAPS = 16'h{TAPS:04X};
  localparam logic [{W-1}:0] ROOT = {W}'d{ROOT};
  function automatic logic [{W-1}:0] f_lo(input logic [{W-1}:0] i);
    logic [{W-1}:0] r; case (i)
{lo}
      default: r='0; endcase f_lo=r; endfunction
  function automatic logic [{W-1}:0] f_hi(input logic [{W-1}:0] i);
    logic [{W-1}:0] r; case (i)
{hi}
      default: r='0; endcase f_hi=r; endfunction
  function automatic logic [15:0] f_clo(input logic [{W-1}:0] i);
    logic [15:0] r; case (i)
{clo}
      default: r='0; endcase f_clo=r; endfunction
  function automatic logic [3:0] f_ord(input logic [3:0] lvl);
    logic [3:0] r; case (lvl)
{od}
      default: r='0; endcase f_ord=r; endfunction
  function automatic logic [15:0] lfsr_step(input logic [15:0] s);
    lfsr_step = (s >> 1) ^ (s[0] ? TAPS : 16'h0); endfunction
  function automatic logic [{NV-1}:0] bdd_unrank(input logic [15:0] lfsr_val);
    logic [15:0] R; logic [{W-1}:0] idx; logic [{NV-1}:0] acc; logic [15:0] clo;
    R = lfsr_val % NSOL; idx = ROOT; acc = '0;
    for (int level=0; level<{NV}; level++) begin
      clo = f_clo(idx);
      if (R < clo) begin acc[f_ord(level[3:0])]=1'b0; idx=f_lo(idx); end
      else         begin acc[f_ord(level[3:0])]=1'b1; R=R-clo; idx=f_hi(idx); end
    end
    return acc;
  endfunction
endpackage
"""
    with open(path, "w") as f:
        f.write(pkg)

if __name__ == "__main__":
    import sys
    from collections import Counter
    nsol, nnodes = selftest()
    print(f"#solutions={nsol}  BDD nodes={nnodes}  (vars={NV})")
    emit_sv("bdd_constraint_sampler.sv"); print("emitted bdd_constraint_sampler.sv")
    emit_pkg("../tier1_actor/bdd_unrank_pkg.sv"); print("emitted ../tier1_actor/bdd_unrank_pkg.sv")
    n = int(sys.argv[1]) if len(sys.argv) > 1 else 100000
    st = stream(n)
    with open("ref_stream.txt", "w") as f:
        for idx in st[:20]:
            a, k, p = fields(idx); f.write(f"addr={a:3d} kind={'W' if k else 'R'} prio={p}\n")
    for idx in st[:20]:
        a, k, p = fields(idx); print(f"addr={a:3d} kind={'W' if k else 'R'} prio={p}")
    c = Counter(st); bad = sum(1 for idx in st if not predicate(idx)); exp = n / nsol
    chi = sum((cnt - exp)**2 / exp for cnt in c.values())
    print(f"checked={n} illegal={bad} distinct={len(c)}/{nsol} "
          f"chi2/df~={chi/(nsol-1):.3f} (~1.0 is uniform)")
