// Auto-generated by appC_earlgrey/tools/reggen_actor.py
// Source: pwm.hjson
// DO NOT EDIT: regenerate with `reggen_actor.py pwm.hjson`

package pwm_ral_defs_pkg;
  import actor_ral_pkg::*;

  function void define_pwm_ral(RalActor ral);
    ral.define_reg("ALERT_TEST", 32'h00000000, RAL_WO, 32'h00000000);
    ral.define_field("ALERT_TEST", "fatal_fault", 0, 1, RAL_WO, 32'h0);
    ral.define_reg("REGWEN", 32'h00000004, RAL_W0C, 32'h00000000);
    ral.define_reg("CFG", 32'h00000008, RAL_RW, 32'h00000000);
    ral.define_field("CFG", "CNTR_EN", 31, 1, RAL_RW, 32'h0);
    ral.define_field("CFG", "DC_RESN", 27, 4, RAL_RW, 32'h7);
    ral.define_field("CFG", "CLK_DIV", 0, 27, RAL_RW, 32'h8000);
  endfunction
endpackage
