// Auto-generated by appC_earlgrey/tools/reggen_actor.py
// Source: aon_timer.hjson
// DO NOT EDIT: regenerate with `reggen_actor.py aon_timer.hjson`

package aon_timer_ral_defs_pkg;
  import actor_ral_pkg::*;

  function void define_aon_timer_ral(RalActor ral);
    ral.define_reg("ALERT_TEST", 32'h00000000, RAL_WO, 32'h00000000);
    ral.define_field("ALERT_TEST", "fatal_fault", 0, 1, RAL_WO, 32'h0);
    ral.define_reg("WKUP_CTRL", 32'h00000004, RAL_RW, 32'h00000000);
    ral.define_field("WKUP_CTRL", "enable", 0, 1, RAL_RW, 32'h0);
    ral.define_field("WKUP_CTRL", "prescaler", 1, 12, RAL_RW, 32'h0);
    ral.define_reg("WKUP_THOLD_HI", 32'h00000008, RAL_RW, 32'h00000000);
    ral.define_field("WKUP_THOLD_HI", "threshold_hi", 0, 32, RAL_RW, 32'h0);
    ral.define_reg("WKUP_THOLD_LO", 32'h0000000C, RAL_RW, 32'h00000000);
    ral.define_field("WKUP_THOLD_LO", "threshold_lo", 0, 32, RAL_RW, 32'h0);
    ral.define_reg("WKUP_COUNT_HI", 32'h00000010, RAL_RW, 32'h00000000);
    ral.define_field("WKUP_COUNT_HI", "count_hi", 0, 32, RAL_RW, 32'h0);
    ral.define_reg("WKUP_COUNT_LO", 32'h00000014, RAL_RW, 32'h00000000);
    ral.define_field("WKUP_COUNT_LO", "count_lo", 0, 32, RAL_RW, 32'h0);
    ral.define_reg("WDOG_REGWEN", 32'h00000018, RAL_W0C, 32'h00000000);
    ral.define_field("WDOG_REGWEN", "regwen", 0, 1, RAL_W0C, 32'h1);
    ral.define_reg("WDOG_CTRL", 32'h0000001C, RAL_RW, 32'h00000000);
    ral.define_field("WDOG_CTRL", "enable", 0, 1, RAL_RW, 32'h0);
    ral.define_field("WDOG_CTRL", "pause_in_sleep", 1, 1, RAL_RW, 32'h0);
    ral.define_reg("WDOG_BARK_THOLD", 32'h00000020, RAL_RW, 32'h00000000);
    ral.define_field("WDOG_BARK_THOLD", "threshold", 0, 32, RAL_RW, 32'h0);
    ral.define_reg("WDOG_BITE_THOLD", 32'h00000024, RAL_RW, 32'h00000000);
    ral.define_field("WDOG_BITE_THOLD", "threshold", 0, 32, RAL_RW, 32'h0);
    ral.define_reg("WDOG_COUNT", 32'h00000028, RAL_RW, 32'h00000000);
    ral.define_field("WDOG_COUNT", "count", 0, 32, RAL_RW, 32'h0);
    ral.define_reg("INTR_STATE", 32'h0000002C, RAL_W1C, 32'h00000000);
    ral.define_field("INTR_STATE", "wkup_timer_expired", 0, 1, RAL_W1C, 32'h0);
    ral.define_field("INTR_STATE", "wdog_timer_bark", 1, 1, RAL_W1C, 32'h0);
    ral.define_reg("INTR_TEST", 32'h00000030, RAL_WO, 32'h00000000);
    ral.define_field("INTR_TEST", "wkup_timer_expired", 0, 1, RAL_WO, 32'h0);
    ral.define_field("INTR_TEST", "wdog_timer_bark", 1, 1, RAL_WO, 32'h0);
    ral.define_reg("WKUP_CAUSE", 32'h00000034, RAL_W0C, 32'h00000000);
    ral.define_field("WKUP_CAUSE", "cause", 0, 1, RAL_W0C, 32'h0);
  endfunction
endpackage
