// earlgrey_memory_map_pkg.sv
//
// Top-level memory map for top_earlgrey, transcribed from
// hw/top_earlgrey/doc/memory_map.md (which is auto-generated by
// util/topgen.py from hw/top_earlgrey/data/top_earlgrey.hjson).
//
// In real verification, each test that addresses a CSR uses the RAL
// model to look up the address; the actor framework's RalActor does
// the same. These constants are the single source of truth that the
// chip-level env uses to wire xbar address regions and the test code
// uses to do CSR access by name.

package earlgrey_memory_map_pkg;

  // ---- Peripheral xbar (peripheral region 0x4000_0000 - 0x40FF_FFFF) ----
  parameter logic [31:0] EG_UART0_BASE          = 32'h4000_0000;
  parameter logic [31:0] EG_UART1_BASE          = 32'h4001_0000;
  parameter logic [31:0] EG_UART2_BASE          = 32'h4002_0000;
  parameter logic [31:0] EG_UART3_BASE          = 32'h4003_0000;
  parameter logic [31:0] EG_GPIO_BASE           = 32'h4004_0000;
  parameter logic [31:0] EG_SPI_DEVICE_BASE     = 32'h4005_0000;
  parameter logic [31:0] EG_I2C0_BASE           = 32'h4008_0000;
  parameter logic [31:0] EG_I2C1_BASE           = 32'h4009_0000;
  parameter logic [31:0] EG_I2C2_BASE           = 32'h400A_0000;
  parameter logic [31:0] EG_PATTGEN_BASE        = 32'h400E_0000;
  parameter logic [31:0] EG_RV_TIMER_BASE       = 32'h4010_0000;
  parameter logic [31:0] EG_OTP_CTRL_BASE       = 32'h4013_0000;
  parameter logic [31:0] EG_LC_CTRL_BASE        = 32'h4014_0000;
  parameter logic [31:0] EG_ALERT_HANDLER_BASE  = 32'h4015_0000;
  parameter logic [31:0] EG_SPI_HOST0_BASE      = 32'h4030_0000;
  parameter logic [31:0] EG_SPI_HOST1_BASE      = 32'h4031_0000;
  parameter logic [31:0] EG_USBDEV_BASE         = 32'h4032_0000;

  // ---- Always-on (AON) sub-bus ----
  parameter logic [31:0] EG_PWRMGR_AON_BASE     = 32'h4040_0000;
  parameter logic [31:0] EG_RSTMGR_AON_BASE     = 32'h4041_0000;
  parameter logic [31:0] EG_CLKMGR_AON_BASE     = 32'h4042_0000;
  parameter logic [31:0] EG_SYSRST_CTRL_AON     = 32'h4043_0000;
  parameter logic [31:0] EG_ADC_CTRL_AON_BASE   = 32'h4044_0000;
  parameter logic [31:0] EG_PWM_AON_BASE        = 32'h4045_0000;
  parameter logic [31:0] EG_PINMUX_AON_BASE     = 32'h4046_0000;
  parameter logic [31:0] EG_AON_TIMER_AON_BASE  = 32'h4047_0000;
  parameter logic [31:0] EG_AST_BASE            = 32'h4048_0000;
  parameter logic [31:0] EG_SENSOR_CTRL_AON     = 32'h4049_0000;
  parameter logic [31:0] EG_SRAM_CTRL_RET_BASE  = 32'h4050_0000;

  // ---- Main xbar (security/crypto/main region 0x4100_0000 - 0x41FF_FFFF) ----
  parameter logic [31:0] EG_FLASH_CTRL_BASE     = 32'h4100_0000;
  parameter logic [31:0] EG_AES_BASE            = 32'h4110_0000;
  parameter logic [31:0] EG_HMAC_BASE           = 32'h4111_0000;
  parameter logic [31:0] EG_KMAC_BASE           = 32'h4112_0000;
  parameter logic [31:0] EG_OTBN_BASE           = 32'h4113_0000;
  parameter logic [31:0] EG_KEYMGR_BASE         = 32'h4114_0000;
  parameter logic [31:0] EG_CSRNG_BASE          = 32'h4115_0000;
  parameter logic [31:0] EG_ENTROPY_SRC_BASE    = 32'h4116_0000;
  parameter logic [31:0] EG_EDN0_BASE           = 32'h4117_0000;
  parameter logic [31:0] EG_EDN1_BASE           = 32'h4118_0000;
  parameter logic [31:0] EG_SRAM_CTRL_MAIN_BASE = 32'h411C_0000;
  parameter logic [31:0] EG_ROM_CTRL_BASE       = 32'h411E_0000;
  parameter logic [31:0] EG_RV_CORE_IBEX_BASE   = 32'h411F_0000;
  parameter logic [31:0] EG_RV_DM_REGS_BASE     = 32'h4120_0000;

  // ---- PLIC (interrupt controller) ----
  parameter logic [31:0] EG_RV_PLIC_BASE        = 32'h4800_0000;

  // ---- Memory blocks ----
  parameter logic [31:0] EG_ROM_MEM_BASE        = 32'h0000_8000;
  parameter logic [31:0] EG_ROM_MEM_SIZE        = 32'h0000_8000;     // 32 KB
  parameter logic [31:0] EG_RV_DM_MEM_BASE      = 32'h0001_0000;
  parameter logic [31:0] EG_SRAM_MAIN_BASE      = 32'h1000_0000;
  parameter logic [31:0] EG_SRAM_MAIN_SIZE      = 32'h0002_0000;     // 128 KB
  parameter logic [31:0] EG_FLASH_MEM_BASE      = 32'h2000_0000;
  parameter logic [31:0] EG_FLASH_MEM_SIZE      = 32'h0010_0000;     // 1 MB
  parameter logic [31:0] EG_SRAM_RET_BASE       = 32'h4060_0000;
  parameter logic [31:0] EG_SRAM_RET_SIZE       = 32'h0000_1000;     // 4 KB

  // Coarse routing masks for the three xbar tiers
  parameter logic [31:0] EG_PERI_XBAR_MASK      = 32'hFF00_0000;
  parameter logic [31:0] EG_PERI_XBAR_BASE      = 32'h4000_0000;
  parameter logic [31:0] EG_AON_XBAR_MASK       = 32'hFFE0_0000;
  parameter logic [31:0] EG_AON_XBAR_BASE       = 32'h4040_0000;
  parameter logic [31:0] EG_MAIN_XBAR_MASK      = 32'hFF00_0000;
  parameter logic [31:0] EG_MAIN_XBAR_BASE      = 32'h4100_0000;

  // ---- Number of instances of each multi-instance IP ----
  parameter int unsigned EG_NUM_UART            = 4;
  parameter int unsigned EG_NUM_I2C             = 3;
  parameter int unsigned EG_NUM_SPI_HOST        = 2;
  parameter int unsigned EG_NUM_EDN             = 2;
  parameter int unsigned EG_NUM_RV_CORE_IBEX    = 1;     // single Ibex with internal lockstep pair

  // ---- Earlgrey alert IDs (subset; full list is in alert_handler_reg_pkg) ----
  parameter int EG_ALERT_UART0_FATAL_FAULT      = 0;
  parameter int EG_ALERT_AON_TIMER_FATAL        = 30;
  parameter int EG_ALERT_FLASH_CTRL_FATAL       = 25;
  parameter int EG_ALERT_LC_CTRL_FATAL_PROG     = 19;
  parameter int EG_ALERT_OTBN_FATAL             = 33;
  parameter int EG_ALERT_KEYMGR_FATAL           = 27;
  parameter int EG_ALERT_KMAC_FATAL             = 35;
  parameter int EG_ALERT_AES_FATAL              = 36;
  parameter int EG_ALERT_ROM_CTRL_FATAL         = 41;
  parameter int EG_ALERT_RV_CORE_IBEX_FATAL_SW  = 67;

  // ---- Earlgrey reset domains ----
  typedef enum logic [3:0] {
    EG_RST_POR        = 0,   // power-on reset (deepest)
    EG_RST_LIFECYCLE  = 1,   // lifecycle-controlled
    EG_RST_SYS        = 2,   // system reset (CPU + most IPs)
    EG_RST_USB        = 3,   // USB-only
    EG_RST_AON        = 4,   // always-on (rare; only on chip reset)
    EG_RST_DEBUG      = 5    // JTAG-driven
  } eg_reset_domain_e;

  // ---- Earlgrey power states (matches pwrmgr_pkg::pwr_state_e) ----
  typedef enum logic [3:0] {
    EG_PWR_RESET            = 0,
    EG_PWR_LOW_POWER        = 1,
    EG_PWR_ACTIVE           = 2,
    EG_PWR_FAST_WAKEUP      = 3,
    EG_PWR_LOW_POWER_REQ    = 4,
    EG_PWR_DEEP_SLEEP       = 5
  } eg_pwr_state_e;

  // ---- Earlgrey lifecycle states (subset of LcState_e) ----
  typedef enum logic [4:0] {
    EG_LC_RAW             = 0,
    EG_LC_TEST_UNLOCKED0  = 1,
    EG_LC_TEST_LOCKED0    = 2,
    EG_LC_DEV             = 7,
    EG_LC_PROD            = 9,
    EG_LC_PROD_END        = 10,
    EG_LC_RMA             = 11,
    EG_LC_SCRAP           = 12
  } eg_lc_state_e;

endpackage
