// Auto-generated by appC_earlgrey/tools/reggen_actor.py
// Source: aes.hjson
// DO NOT EDIT: regenerate with `reggen_actor.py aes.hjson`

package aes_ral_defs_pkg;
  import actor_ral_pkg::*;

  function void define_aes_ral(RalActor ral);
    ral.define_reg("ALERT_TEST", 32'h00000000, RAL_WO, 32'h00000000);
    ral.define_field("ALERT_TEST", "recov_ctrl_update_err", 0, 1, RAL_WO, 32'h0);
    ral.define_field("ALERT_TEST", "fatal_fault", 1, 1, RAL_WO, 32'h0);
    ral.define_reg("CTRL_SHADOWED", 32'h00000004, RAL_RW, 32'h00000000);
    ral.define_field("CTRL_SHADOWED", "OPERATION", 0, 2, RAL_RW, 32'h1);
    ral.define_field("CTRL_SHADOWED", "MODE", 2, 6, RAL_RW, 32'h3F);
    ral.define_field("CTRL_SHADOWED", "KEY_LEN", 8, 3, RAL_RW, 32'h1);
    ral.define_field("CTRL_SHADOWED", "SIDELOAD", 11, 1, RAL_RW, 32'h0);
    ral.define_field("CTRL_SHADOWED", "PRNG_RESEED_RATE", 12, 3, RAL_RW, 32'h1);
    ral.define_field("CTRL_SHADOWED", "MANUAL_OPERATION", 15, 1, RAL_RW, 32'h0);
    ral.define_reg("CTRL_AUX_SHADOWED", 32'h00000008, RAL_RW, 32'h00000000);
    ral.define_field("CTRL_AUX_SHADOWED", "KEY_TOUCH_FORCES_RESEED", 0, 1, RAL_RW, 32'h1);
    ral.define_field("CTRL_AUX_SHADOWED", "FORCE_MASKS", 1, 1, RAL_RW, 32'h0);
    ral.define_reg("CTRL_AUX_REGWEN", 32'h0000000C, RAL_W0C, 32'h00000000);
    ral.define_reg("TRIGGER", 32'h00000010, RAL_WO, 32'h00000000);
    ral.define_field("TRIGGER", "START", 0, 1, RAL_WO, 32'h0);
    ral.define_field("TRIGGER", "KEY_IV_DATA_IN_CLEAR", 1, 1, RAL_WO, 32'h1);
    ral.define_field("TRIGGER", "DATA_OUT_CLEAR", 2, 1, RAL_WO, 32'h1);
    ral.define_field("TRIGGER", "PRNG_RESEED", 3, 1, RAL_WO, 32'h1);
    ral.define_reg("STATUS", 32'h00000014, RAL_RO, 32'h00000000);
    ral.define_field("STATUS", "IDLE", 0, 1, RAL_RO, 32'h0);
    ral.define_field("STATUS", "STALL", 1, 1, RAL_RO, 32'h0);
    ral.define_field("STATUS", "OUTPUT_LOST", 2, 1, RAL_RO, 32'h0);
    ral.define_field("STATUS", "OUTPUT_VALID", 3, 1, RAL_RO, 32'h0);
    ral.define_field("STATUS", "INPUT_READY", 4, 1, RAL_RO, 32'h0);
    ral.define_field("STATUS", "ALERT_RECOV_CTRL_UPDATE_ERR", 5, 1, RAL_RO, 32'h0);
    ral.define_field("STATUS", "ALERT_FATAL_FAULT", 6, 1, RAL_RO, 32'h0);
    ral.define_reg("CTRL_GCM_SHADOWED", 32'h00000018, RAL_RW, 32'h00000000);
    ral.define_field("CTRL_GCM_SHADOWED", "PHASE", 0, 6, RAL_RW, 32'h1);
    ral.define_field("CTRL_GCM_SHADOWED", "NUM_VALID_BYTES", 6, 5, RAL_RW, 32'h10);
  endfunction
endpackage
