// Auto-generated by appC_earlgrey/tools/reggen_actor.py
// Source: lc_ctrl.hjson
// DO NOT EDIT: regenerate with `reggen_actor.py lc_ctrl.hjson`

package lc_ctrl_ral_defs_pkg;
  import actor_ral_pkg::*;

  function void define_lc_ctrl_ral(RalActor ral);
    ral.define_reg("ALERT_TEST", 32'h00000000, RAL_WO, 32'h00000000);
    ral.define_field("ALERT_TEST", "fatal_prog_error", 0, 1, RAL_WO, 32'h0);
    ral.define_field("ALERT_TEST", "fatal_state_error", 1, 1, RAL_WO, 32'h0);
    ral.define_field("ALERT_TEST", "fatal_bus_integ_error", 2, 1, RAL_WO, 32'h0);
    ral.define_reg("STATUS", 32'h00000004, RAL_RO, 32'h00000000);
    ral.define_field("STATUS", "INITIALIZED", 0, 1, RAL_RO, 32'h0);
    ral.define_field("STATUS", "READY", 1, 1, RAL_RO, 32'h0);
    ral.define_field("STATUS", "EXT_CLOCK_SWITCHED", 2, 1, RAL_RO, 32'h0);
    ral.define_field("STATUS", "TRANSITION_SUCCESSFUL", 3, 1, RAL_RO, 32'h0);
    ral.define_field("STATUS", "TRANSITION_COUNT_ERROR", 4, 1, RAL_RO, 32'h0);
    ral.define_field("STATUS", "TRANSITION_ERROR", 5, 1, RAL_RO, 32'h0);
    ral.define_field("STATUS", "TOKEN_ERROR", 6, 1, RAL_RO, 32'h0);
    ral.define_field("STATUS", "NVM_RMA_ERROR", 7, 1, RAL_RO, 32'h0);
    ral.define_field("STATUS", "OTP_ERROR", 8, 1, RAL_RO, 32'h0);
    ral.define_field("STATUS", "STATE_ERROR", 9, 1, RAL_RO, 32'h0);
    ral.define_field("STATUS", "BUS_INTEG_ERROR", 10, 1, RAL_RO, 32'h0);
    ral.define_field("STATUS", "OTP_PARTITION_ERROR", 11, 1, RAL_RO, 32'h0);
    ral.define_reg("CLAIM_TRANSITION_IF_REGWEN", 32'h00000008, RAL_W0C, 32'h00000000);
    ral.define_reg("CLAIM_TRANSITION_IF", 32'h0000000C, RAL_RW, 32'h00000000);
    ral.define_field("CLAIM_TRANSITION_IF", "MUTEX", 0, 8, RAL_RW, 32'h0);
    ral.define_reg("TRANSITION_REGWEN", 32'h00000010, RAL_RO, 32'h00000000);
    ral.define_reg("TRANSITION_CMD", 32'h00000014, RAL_W1C, 32'h00000000);
    ral.define_field("TRANSITION_CMD", "START", 0, 1, RAL_W1C, 32'h0);
    ral.define_reg("TRANSITION_CTRL", 32'h00000018, RAL_RW, 32'h00000000);
    ral.define_field("TRANSITION_CTRL", "EXT_CLOCK_EN", 0, 1, RAL_RW, 32'h0);
    ral.define_field("TRANSITION_CTRL", "VOLATILE_RAW_UNLOCK", 1, 1, RAL_RW, 32'h0);
    ral.define_reg("TRANSITION_TARGET", 32'h0000001C, RAL_RW, 32'h00000000);
    ral.define_field("TRANSITION_TARGET", "STATE", 0, 32, RAL_RW, 32'h0);
    ral.define_reg("OTP_VENDOR_TEST_CTRL", 32'h00000020, RAL_RW, 32'h00000000);
    ral.define_reg("OTP_VENDOR_TEST_STATUS", 32'h00000024, RAL_RO, 32'h00000000);
    ral.define_reg("LC_STATE", 32'h00000028, RAL_RO, 32'h00000000);
    ral.define_field("LC_STATE", "STATE", 0, 32, RAL_RO, 32'h0);
    ral.define_reg("LC_TRANSITION_CNT", 32'h0000002C, RAL_RO, 32'h00000000);
    ral.define_field("LC_TRANSITION_CNT", "CNT", 0, 32, RAL_RO, 32'h0);
    ral.define_reg("LC_ID_STATE", 32'h00000030, RAL_RO, 32'h00000000);
    ral.define_field("LC_ID_STATE", "STATE", 0, 32, RAL_RO, 32'h0);
    ral.define_reg("HW_REVISION0", 32'h00000034, RAL_RO, 32'h00000000);
    ral.define_field("HW_REVISION0", "SILICON_CREATOR_ID", 0, 32, RAL_RO, 32'h0);
    ral.define_field("HW_REVISION0", "PRODUCT_ID", 0, 32, RAL_RO, 32'h0);
    ral.define_reg("HW_REVISION1", 32'h00000038, RAL_RO, 32'h00000000);
    ral.define_field("HW_REVISION1", "REVISION_ID", 0, 32, RAL_RO, 32'h0);
    ral.define_field("HW_REVISION1", "RESERVED", 0, 32, RAL_RO, 32'h0);
  endfunction
endpackage
