// Auto-generated by appC_earlgrey/tools/reggen_actor.py
// Source: pinmux.hjson
// DO NOT EDIT: regenerate with `reggen_actor.py pinmux.hjson`

package pinmux_ral_defs_pkg;
  import actor_ral_pkg::*;

  function void define_pinmux_ral(RalActor ral);
  endfunction
endpackage
