// Auto-generated by appC_earlgrey/tools/reggen_actor.py
// Source: otp_ctrl.hjson
// DO NOT EDIT: regenerate with `reggen_actor.py otp_ctrl.hjson`

package otp_ctrl_ral_defs_pkg;
  import actor_ral_pkg::*;

  function void define_otp_ctrl_ral(RalActor ral);
    ral.define_reg("INTR_STATE", 32'h00000000, RAL_W1C, 32'h00000000);
    ral.define_field("INTR_STATE", "otp_operation_done", 0, 1, RAL_RW, 32'h0);
    ral.define_field("INTR_STATE", "otp_error", 1, 1, RAL_RW, 32'h0);
    ral.define_reg("INTR_ENABLE", 32'h00000004, RAL_RW, 32'h00000000);
    ral.define_field("INTR_ENABLE", "otp_operation_done", 0, 1, RAL_RW, 32'h0);
    ral.define_field("INTR_ENABLE", "otp_error", 1, 1, RAL_RW, 32'h0);
    ral.define_reg("INTR_TEST", 32'h00000008, RAL_WO, 32'h00000000);
    ral.define_field("INTR_TEST", "otp_operation_done", 0, 1, RAL_WO, 32'h0);
    ral.define_field("INTR_TEST", "otp_error", 1, 1, RAL_WO, 32'h0);
    ral.define_reg("ALERT_TEST", 32'h0000000C, RAL_WO, 32'h00000000);
    ral.define_field("ALERT_TEST", "fatal_macro_error", 0, 1, RAL_WO, 32'h0);
    ral.define_field("ALERT_TEST", "fatal_check_error", 1, 1, RAL_WO, 32'h0);
    ral.define_field("ALERT_TEST", "fatal_bus_integ_error", 2, 1, RAL_WO, 32'h0);
    ral.define_field("ALERT_TEST", "fatal_prim_otp_alert", 3, 1, RAL_WO, 32'h0);
    ral.define_field("ALERT_TEST", "recov_prim_otp_alert", 4, 1, RAL_WO, 32'h0);
    ral.define_reg("STATUS", 32'h00000010, RAL_RO, 32'h00000000);
    ral.define_field("STATUS", "PARTITION_ERROR", 0, 1, RAL_RO, 32'h0);
    ral.define_field("STATUS", "DAI_ERROR", 1, 1, RAL_RO, 32'h0);
    ral.define_field("STATUS", "LCI_ERROR", 2, 1, RAL_RO, 32'h0);
    ral.define_field("STATUS", "TIMEOUT_ERROR", 3, 1, RAL_RO, 32'h0);
    ral.define_field("STATUS", "LFSR_FSM_ERROR", 4, 1, RAL_RO, 32'h0);
    ral.define_field("STATUS", "SCRAMBLING_FSM_ERROR", 5, 1, RAL_RO, 32'h0);
    ral.define_field("STATUS", "KEY_DERIV_FSM_ERROR", 6, 1, RAL_RO, 32'h0);
    ral.define_field("STATUS", "BUS_INTEG_ERROR", 7, 1, RAL_RO, 32'h0);
    ral.define_field("STATUS", "DAI_IDLE", 8, 1, RAL_RO, 32'h0);
    ral.define_field("STATUS", "CHECK_PENDING", 9, 1, RAL_RO, 32'h0);
    ral.define_reg("PARTITION_STATUS_0", 32'h00000014, RAL_RO, 32'h00000000);
    ral.define_field("PARTITION_STATUS_0", "VENDOR_TEST_ERROR", 0, 1, RAL_RO, 32'h0);
    ral.define_field("PARTITION_STATUS_0", "CREATOR_SW_CFG_ERROR", 1, 1, RAL_RO, 32'h0);
    ral.define_field("PARTITION_STATUS_0", "OWNER_SW_CFG_ERROR", 2, 1, RAL_RO, 32'h0);
    ral.define_field("PARTITION_STATUS_0", "ROT_CREATOR_AUTH_CODESIGN_ERROR", 3, 1, RAL_RO, 32'h0);
    ral.define_field("PARTITION_STATUS_0", "ROT_CREATOR_AUTH_STATE_ERROR", 4, 1, RAL_RO, 32'h0);
    ral.define_field("PARTITION_STATUS_0", "HW_CFG0_ERROR", 5, 1, RAL_RO, 32'h0);
    ral.define_field("PARTITION_STATUS_0", "HW_CFG1_ERROR", 6, 1, RAL_RO, 32'h0);
    ral.define_field("PARTITION_STATUS_0", "SECRET0_ERROR", 7, 1, RAL_RO, 32'h0);
    ral.define_field("PARTITION_STATUS_0", "SECRET1_ERROR", 8, 1, RAL_RO, 32'h0);
    ral.define_field("PARTITION_STATUS_0", "SECRET2_ERROR", 9, 1, RAL_RO, 32'h0);
    ral.define_field("PARTITION_STATUS_0", "LIFE_CYCLE_ERROR", 10, 1, RAL_RO, 32'h0);
    ral.define_reg("DIRECT_ACCESS_REGWEN", 32'h00000018, RAL_W0C, 32'h00000000);
    ral.define_reg("DIRECT_ACCESS_CMD", 32'h0000001C, RAL_W1C, 32'h00000000);
    ral.define_field("DIRECT_ACCESS_CMD", "RD", 0, 1, RAL_W1C, 32'h0);
    ral.define_field("DIRECT_ACCESS_CMD", "WR", 1, 1, RAL_W1C, 32'h0);
    ral.define_field("DIRECT_ACCESS_CMD", "DIGEST", 2, 1, RAL_W1C, 32'h0);
    ral.define_field("DIRECT_ACCESS_CMD", "ZEROIZE", 3, 1, RAL_W1C, 32'h0);
    ral.define_reg("DIRECT_ACCESS_ADDRESS", 32'h00000020, RAL_RW, 32'h00000000);
    ral.define_reg("CHECK_TRIGGER_REGWEN", 32'h00000024, RAL_W0C, 32'h00000000);
    ral.define_reg("CHECK_TRIGGER", 32'h00000028, RAL_W1C, 32'h00000000);
    ral.define_field("CHECK_TRIGGER", "INTEGRITY", 0, 1, RAL_W1C, 32'h0);
    ral.define_field("CHECK_TRIGGER", "CONSISTENCY", 1, 1, RAL_W1C, 32'h0);
    ral.define_reg("CHECK_REGWEN", 32'h0000002C, RAL_W0C, 32'h00000000);
    ral.define_reg("CHECK_TIMEOUT", 32'h00000030, RAL_RW, 32'h00000000);
    ral.define_reg("INTEGRITY_CHECK_PERIOD", 32'h00000034, RAL_RW, 32'h00000000);
    ral.define_reg("CONSISTENCY_CHECK_PERIOD", 32'h00000038, RAL_RW, 32'h00000000);
    ral.define_reg("VENDOR_TEST_READ_LOCK", 32'h0000003C, RAL_W0C, 32'h00000000);
    ral.define_reg("CREATOR_SW_CFG_READ_LOCK", 32'h00000040, RAL_W0C, 32'h00000000);
    ral.define_reg("OWNER_SW_CFG_READ_LOCK", 32'h00000044, RAL_W0C, 32'h00000000);
    ral.define_reg("ROT_CREATOR_AUTH_CODESIGN_READ_LOCK", 32'h00000048, RAL_W0C, 32'h00000000);
    ral.define_reg("ROT_CREATOR_AUTH_STATE_READ_LOCK", 32'h0000004C, RAL_W0C, 32'h00000000);
  endfunction
endpackage
