// Auto-generated by appC_earlgrey/tools/reggen_actor.py
// Source: keymgr.hjson
// DO NOT EDIT: regenerate with `reggen_actor.py keymgr.hjson`

package keymgr_ral_defs_pkg;
  import actor_ral_pkg::*;

  function void define_keymgr_ral(RalActor ral);
    ral.define_reg("INTR_STATE", 32'h00000000, RAL_W1C, 32'h00000000);
    ral.define_field("INTR_STATE", "op_done", 0, 1, RAL_RW, 32'h0);
    ral.define_reg("INTR_ENABLE", 32'h00000004, RAL_RW, 32'h00000000);
    ral.define_field("INTR_ENABLE", "op_done", 0, 1, RAL_RW, 32'h0);
    ral.define_reg("INTR_TEST", 32'h00000008, RAL_WO, 32'h00000000);
    ral.define_field("INTR_TEST", "op_done", 0, 1, RAL_WO, 32'h0);
    ral.define_reg("ALERT_TEST", 32'h0000000C, RAL_WO, 32'h00000000);
    ral.define_field("ALERT_TEST", "recov_operation_err", 0, 1, RAL_WO, 32'h0);
    ral.define_field("ALERT_TEST", "fatal_fault_err", 1, 1, RAL_WO, 32'h0);
    ral.define_reg("CFG_REGWEN", 32'h00000010, RAL_RO, 32'h00000000);
    ral.define_field("CFG_REGWEN", "EN", 0, 1, RAL_RO, 32'h1);
    ral.define_reg("START", 32'h00000014, RAL_RW, 32'h00000000);
    ral.define_field("START", "EN", 0, 1, RAL_RW, 32'h0);
    ral.define_reg("CONTROL_SHADOWED", 32'h00000018, RAL_RW, 32'h00000000);
    ral.define_field("CONTROL_SHADOWED", "OPERATION", 4, 3, RAL_RW, 32'h1);
    ral.define_field("CONTROL_SHADOWED", "CDI_SEL", 7, 1, RAL_RW, 32'h0);
    ral.define_field("CONTROL_SHADOWED", "DEST_SEL", 12, 2, RAL_RW, 32'h0);
    ral.define_reg("SIDELOAD_CLEAR", 32'h0000001C, RAL_RW, 32'h00000000);
    ral.define_field("SIDELOAD_CLEAR", "VAL", 0, 3, RAL_RW, 32'h0);
    ral.define_reg("RESEED_INTERVAL_REGWEN", 32'h00000020, RAL_W0C, 32'h00000000);
    ral.define_field("RESEED_INTERVAL_REGWEN", "EN", 0, 1, RAL_W0C, 32'h1);
    ral.define_reg("RESEED_INTERVAL_SHADOWED", 32'h00000024, RAL_RW, 32'h00000000);
    ral.define_field("RESEED_INTERVAL_SHADOWED", "VAL", 0, 16, RAL_RW, 32'h100);
    ral.define_reg("SW_BINDING_REGWEN", 32'h00000028, RAL_W0C, 32'h00000000);
    ral.define_field("SW_BINDING_REGWEN", "EN", 0, 1, RAL_W0C, 32'h1);
    ral.define_reg("MAX_CREATOR_KEY_VER_REGWEN", 32'h0000002C, RAL_W0C, 32'h00000000);
    ral.define_field("MAX_CREATOR_KEY_VER_REGWEN", "EN", 0, 1, RAL_W0C, 32'h1);
    ral.define_reg("MAX_CREATOR_KEY_VER_SHADOWED", 32'h00000030, RAL_RW, 32'h00000000);
    ral.define_field("MAX_CREATOR_KEY_VER_SHADOWED", "VAL", 0, 32, RAL_RW, 32'h0);
    ral.define_reg("MAX_OWNER_INT_KEY_VER_REGWEN", 32'h00000034, RAL_W0C, 32'h00000000);
    ral.define_field("MAX_OWNER_INT_KEY_VER_REGWEN", "EN", 0, 1, RAL_W0C, 32'h1);
    ral.define_reg("MAX_OWNER_INT_KEY_VER_SHADOWED", 32'h00000038, RAL_RW, 32'h00000000);
    ral.define_field("MAX_OWNER_INT_KEY_VER_SHADOWED", "VAL", 0, 32, RAL_RW, 32'h1);
    ral.define_reg("MAX_OWNER_KEY_VER_REGWEN", 32'h0000003C, RAL_W0C, 32'h00000000);
    ral.define_field("MAX_OWNER_KEY_VER_REGWEN", "EN", 0, 1, RAL_W0C, 32'h1);
    ral.define_reg("MAX_OWNER_KEY_VER_SHADOWED", 32'h00000040, RAL_RW, 32'h00000000);
    ral.define_field("MAX_OWNER_KEY_VER_SHADOWED", "VAL", 0, 32, RAL_RW, 32'h0);
    ral.define_reg("WORKING_STATE", 32'h00000044, RAL_RO, 32'h00000000);
    ral.define_field("WORKING_STATE", "STATE", 0, 3, RAL_RO, 32'h0);
    ral.define_reg("OP_STATUS", 32'h00000048, RAL_W1C, 32'h00000000);
    ral.define_field("OP_STATUS", "STATUS", 0, 2, RAL_W1C, 32'h0);
    ral.define_reg("ERR_CODE", 32'h0000004C, RAL_W1C, 32'h00000000);
    ral.define_field("ERR_CODE", "INVALID_OP", 0, 1, RAL_W1C, 32'h0);
    ral.define_field("ERR_CODE", "INVALID_KMAC_INPUT", 1, 1, RAL_W1C, 32'h0);
    ral.define_field("ERR_CODE", "INVALID_SHADOW_UPDATE", 2, 1, RAL_W1C, 32'h0);
    ral.define_reg("FAULT_STATUS", 32'h00000050, RAL_RO, 32'h00000000);
    ral.define_field("FAULT_STATUS", "CMD", 0, 1, RAL_RO, 32'h0);
    ral.define_field("FAULT_STATUS", "KMAC_FSM", 1, 1, RAL_RO, 32'h0);
    ral.define_field("FAULT_STATUS", "KMAC_DONE", 2, 1, RAL_RO, 32'h0);
    ral.define_field("FAULT_STATUS", "KMAC_OP", 3, 1, RAL_RO, 32'h0);
    ral.define_field("FAULT_STATUS", "KMAC_OUT", 4, 1, RAL_RO, 32'h0);
    ral.define_field("FAULT_STATUS", "REGFILE_INTG", 5, 1, RAL_RO, 32'h0);
    ral.define_field("FAULT_STATUS", "SHADOW", 6, 1, RAL_RO, 32'h0);
    ral.define_field("FAULT_STATUS", "CTRL_FSM_INTG", 7, 1, RAL_RO, 32'h0);
    ral.define_field("FAULT_STATUS", "CTRL_FSM_CHK", 8, 1, RAL_RO, 32'h0);
    ral.define_field("FAULT_STATUS", "CTRL_FSM_CNT", 9, 1, RAL_RO, 32'h0);
    ral.define_field("FAULT_STATUS", "RESEED_CNT", 10, 1, RAL_RO, 32'h0);
    ral.define_field("FAULT_STATUS", "SIDE_CTRL_FSM", 11, 1, RAL_RO, 32'h0);
    ral.define_field("FAULT_STATUS", "SIDE_CTRL_SEL", 12, 1, RAL_RO, 32'h0);
    ral.define_field("FAULT_STATUS", "KEY_ECC", 13, 1, RAL_RO, 32'h0);
    ral.define_reg("DEBUG", 32'h00000054, RAL_W0C, 32'h00000000);
    ral.define_field("DEBUG", "INVALID_CREATOR_SEED", 0, 1, RAL_W0C, 32'h0);
    ral.define_field("DEBUG", "INVALID_OWNER_SEED", 1, 1, RAL_W0C, 32'h0);
    ral.define_field("DEBUG", "INVALID_DEV_ID", 2, 1, RAL_W0C, 32'h0);
    ral.define_field("DEBUG", "INVALID_HEALTH_STATE", 3, 1, RAL_W0C, 32'h0);
    ral.define_field("DEBUG", "INVALID_KEY_VERSION", 4, 1, RAL_W0C, 32'h0);
    ral.define_field("DEBUG", "INVALID_KEY", 5, 1, RAL_W0C, 32'h0);
    ral.define_field("DEBUG", "INVALID_DIGEST", 6, 1, RAL_W0C, 32'h0);
  endfunction
endpackage
