// Auto-generated by appC_earlgrey/tools/reggen_actor.py
// Source: kmac.hjson
// DO NOT EDIT: regenerate with `reggen_actor.py kmac.hjson`

package kmac_ral_defs_pkg;
  import actor_ral_pkg::*;

  function void define_kmac_ral(RalActor ral);
    ral.define_reg("INTR_STATE", 32'h00000000, RAL_W1C, 32'h00000000);
    ral.define_field("INTR_STATE", "kmac_done", 0, 1, RAL_RW, 32'h0);
    ral.define_field("INTR_STATE", "fifo_empty", 1, 1, RAL_RW, 32'h0);
    ral.define_field("INTR_STATE", "kmac_err", 2, 1, RAL_RW, 32'h0);
    ral.define_reg("INTR_ENABLE", 32'h00000004, RAL_RW, 32'h00000000);
    ral.define_field("INTR_ENABLE", "kmac_done", 0, 1, RAL_RW, 32'h0);
    ral.define_field("INTR_ENABLE", "fifo_empty", 1, 1, RAL_RW, 32'h0);
    ral.define_field("INTR_ENABLE", "kmac_err", 2, 1, RAL_RW, 32'h0);
    ral.define_reg("INTR_TEST", 32'h00000008, RAL_WO, 32'h00000000);
    ral.define_field("INTR_TEST", "kmac_done", 0, 1, RAL_WO, 32'h0);
    ral.define_field("INTR_TEST", "fifo_empty", 1, 1, RAL_WO, 32'h0);
    ral.define_field("INTR_TEST", "kmac_err", 2, 1, RAL_WO, 32'h0);
    ral.define_reg("ALERT_TEST", 32'h0000000C, RAL_WO, 32'h00000000);
    ral.define_field("ALERT_TEST", "recov_operation_err", 0, 1, RAL_WO, 32'h0);
    ral.define_field("ALERT_TEST", "fatal_fault_err", 1, 1, RAL_WO, 32'h0);
    ral.define_reg("CFG_REGWEN", 32'h00000010, RAL_RO, 32'h00000000);
    ral.define_field("CFG_REGWEN", "en", 0, 1, RAL_RO, 32'h1);
    ral.define_reg("CFG_SHADOWED", 32'h00000014, RAL_RW, 32'h00000000);
    ral.define_field("CFG_SHADOWED", "kmac_en", 0, 1, RAL_RW, 32'h0);
    ral.define_field("CFG_SHADOWED", "kstrength", 1, 3, RAL_RW, 32'h0);
    ral.define_field("CFG_SHADOWED", "mode", 4, 2, RAL_RW, 32'h0);
    ral.define_field("CFG_SHADOWED", "msg_endianness", 8, 1, RAL_RW, 32'h0);
    ral.define_field("CFG_SHADOWED", "state_endianness", 9, 1, RAL_RW, 32'h0);
    ral.define_field("CFG_SHADOWED", "sideload", 12, 1, RAL_RW, 32'h0);
    ral.define_field("CFG_SHADOWED", "entropy_mode", 16, 2, RAL_RW, 32'h0);
    ral.define_field("CFG_SHADOWED", "entropy_fast_process", 19, 1, RAL_RW, 32'h0);
    ral.define_field("CFG_SHADOWED", "msg_mask", 20, 1, RAL_RW, 32'h0);
    ral.define_field("CFG_SHADOWED", "entropy_ready", 24, 1, RAL_RW, 32'h0);
    ral.define_field("CFG_SHADOWED", "en_unsupported_modestrength", 26, 1, RAL_RW, 32'h0);
    ral.define_reg("CMD", 32'h00000018, RAL_W1C, 32'h00000000);
    ral.define_field("CMD", "cmd", 0, 6, RAL_W1C, 32'h0);
    ral.define_field("CMD", "entropy_req", 8, 1, RAL_W1C, 32'h0);
    ral.define_field("CMD", "hash_cnt_clr", 9, 1, RAL_W1C, 32'h0);
    ral.define_field("CMD", "err_processed", 10, 1, RAL_W1C, 32'h0);
    ral.define_reg("STATUS", 32'h0000001C, RAL_RO, 32'h00000000);
    ral.define_field("STATUS", "sha3_idle", 0, 1, RAL_RO, 32'h1);
    ral.define_field("STATUS", "sha3_absorb", 1, 1, RAL_RO, 32'h0);
    ral.define_field("STATUS", "sha3_squeeze", 2, 1, RAL_RO, 32'h0);
    ral.define_field("STATUS", "fifo_depth", 8, 5, RAL_RO, 32'h0);
    ral.define_field("STATUS", "fifo_empty", 14, 1, RAL_RO, 32'h1);
    ral.define_field("STATUS", "fifo_full", 15, 1, RAL_RO, 32'h0);
    ral.define_field("STATUS", "ALERT_FATAL_FAULT", 16, 1, RAL_RO, 32'h0);
    ral.define_field("STATUS", "ALERT_RECOV_CTRL_UPDATE_ERR", 17, 1, RAL_RO, 32'h0);
    ral.define_reg("ENTROPY_PERIOD", 32'h00000020, RAL_RW, 32'h00000000);
    ral.define_field("ENTROPY_PERIOD", "prescaler", 0, 10, RAL_RW, 32'h0);
    ral.define_field("ENTROPY_PERIOD", "wait_timer", 16, 16, RAL_RW, 32'h0);
    ral.define_reg("ENTROPY_REFRESH_HASH_CNT", 32'h00000024, RAL_RO, 32'h00000000);
    ral.define_field("ENTROPY_REFRESH_HASH_CNT", "hash_cnt", 0, 32, RAL_RO, 32'h0);
    ral.define_reg("ENTROPY_REFRESH_THRESHOLD_SHADOWED", 32'h00000028, RAL_RW, 32'h00000000);
    ral.define_field("ENTROPY_REFRESH_THRESHOLD_SHADOWED", "threshold", 0, 32, RAL_RW, 32'h0);
    ral.define_reg("ENTROPY_SEED", 32'h0000002C, RAL_WO, 32'h00000000);
    ral.define_field("ENTROPY_SEED", "seed", 0, 32, RAL_WO, 32'h0);
    ral.define_reg("KEY_LEN", 32'h00000030, RAL_WO, 32'h00000000);
    ral.define_field("KEY_LEN", "len", 0, 3, RAL_WO, 32'h0);
    ral.define_reg("ERR_CODE", 32'h00000034, RAL_RO, 32'h00000000);
    ral.define_field("ERR_CODE", "err_code", 0, 32, RAL_RO, 32'h0);
  endfunction
endpackage
