// Auto-generated by appC_earlgrey/tools/reggen_actor.py
// Source: edn.hjson
// DO NOT EDIT: regenerate with `reggen_actor.py edn.hjson`

package edn_ral_defs_pkg;
  import actor_ral_pkg::*;

  function void define_edn_ral(RalActor ral);
    ral.define_reg("INTR_STATE", 32'h00000000, RAL_W1C, 32'h00000000);
    ral.define_field("INTR_STATE", "edn_cmd_req_done", 0, 1, RAL_RW, 32'h0);
    ral.define_field("INTR_STATE", "edn_fatal_err", 1, 1, RAL_RW, 32'h0);
    ral.define_reg("INTR_ENABLE", 32'h00000004, RAL_RW, 32'h00000000);
    ral.define_field("INTR_ENABLE", "edn_cmd_req_done", 0, 1, RAL_RW, 32'h0);
    ral.define_field("INTR_ENABLE", "edn_fatal_err", 1, 1, RAL_RW, 32'h0);
    ral.define_reg("INTR_TEST", 32'h00000008, RAL_WO, 32'h00000000);
    ral.define_field("INTR_TEST", "edn_cmd_req_done", 0, 1, RAL_WO, 32'h0);
    ral.define_field("INTR_TEST", "edn_fatal_err", 1, 1, RAL_WO, 32'h0);
    ral.define_reg("ALERT_TEST", 32'h0000000C, RAL_WO, 32'h00000000);
    ral.define_field("ALERT_TEST", "recov_alert", 0, 1, RAL_WO, 32'h0);
    ral.define_field("ALERT_TEST", "fatal_alert", 1, 1, RAL_WO, 32'h0);
    ral.define_reg("REGWEN", 32'h00000010, RAL_W0C, 32'h00000000);
    ral.define_reg("CTRL", 32'h00000014, RAL_RW, 32'h00000000);
    ral.define_field("CTRL", "EDN_ENABLE", 0, 4, RAL_RW, 32'h0);
    ral.define_field("CTRL", "BOOT_REQ_MODE", 4, 4, RAL_RW, 32'h0);
    ral.define_field("CTRL", "AUTO_REQ_MODE", 8, 4, RAL_RW, 32'h0);
    ral.define_field("CTRL", "CMD_FIFO_RST", 12, 4, RAL_RW, 32'h0);
    ral.define_reg("BOOT_INS_CMD", 32'h00000018, RAL_RW, 32'h00000000);
    ral.define_field("BOOT_INS_CMD", "BOOT_INS_CMD", 0, 32, RAL_RW, 32'h901);
    ral.define_reg("BOOT_GEN_CMD", 32'h0000001C, RAL_RW, 32'h00000000);
    ral.define_field("BOOT_GEN_CMD", "BOOT_GEN_CMD", 0, 32, RAL_RW, 32'hFFF003);
    ral.define_reg("SW_CMD_REQ", 32'h00000020, RAL_WO, 32'h00000000);
    ral.define_field("SW_CMD_REQ", "SW_CMD_REQ", 0, 32, RAL_WO, 32'h0);
    ral.define_reg("SW_CMD_STS", 32'h00000024, RAL_RO, 32'h00000000);
    ral.define_field("SW_CMD_STS", "CMD_REG_RDY", 0, 1, RAL_RO, 32'h0);
    ral.define_field("SW_CMD_STS", "CMD_RDY", 1, 1, RAL_RO, 32'h0);
    ral.define_field("SW_CMD_STS", "CMD_ACK", 2, 1, RAL_RO, 32'h0);
    ral.define_field("SW_CMD_STS", "CMD_STS", 3, 3, RAL_RO, 32'h0);
    ral.define_reg("HW_CMD_STS", 32'h00000028, RAL_RO, 32'h00000000);
    ral.define_field("HW_CMD_STS", "BOOT_MODE", 0, 1, RAL_RO, 32'h0);
    ral.define_field("HW_CMD_STS", "AUTO_MODE", 1, 1, RAL_RO, 32'h0);
    ral.define_field("HW_CMD_STS", "CMD_TYPE", 2, 4, RAL_RO, 32'h0);
    ral.define_field("HW_CMD_STS", "CMD_ACK", 6, 1, RAL_RO, 32'h0);
    ral.define_field("HW_CMD_STS", "CMD_STS", 7, 3, RAL_RO, 32'h0);
    ral.define_reg("RESEED_CMD", 32'h0000002C, RAL_WO, 32'h00000000);
    ral.define_field("RESEED_CMD", "RESEED_CMD", 0, 32, RAL_WO, 32'h0);
    ral.define_reg("GENERATE_CMD", 32'h00000030, RAL_WO, 32'h00000000);
    ral.define_field("GENERATE_CMD", "GENERATE_CMD", 0, 32, RAL_WO, 32'h0);
    ral.define_reg("MAX_NUM_REQS_BETWEEN_RESEEDS", 32'h00000034, RAL_RW, 32'h00000000);
    ral.define_field("MAX_NUM_REQS_BETWEEN_RESEEDS", "MAX_NUM_REQS_BETWEEN_RESEEDS", 0, 32, RAL_RW, 32'h0);
    ral.define_reg("RECOV_ALERT_STS", 32'h00000038, RAL_W0C, 32'h00000000);
    ral.define_field("RECOV_ALERT_STS", "EDN_ENABLE_FIELD_ALERT", 0, 1, RAL_W0C, 32'h0);
    ral.define_field("RECOV_ALERT_STS", "BOOT_REQ_MODE_FIELD_ALERT", 1, 1, RAL_W0C, 32'h0);
    ral.define_field("RECOV_ALERT_STS", "AUTO_REQ_MODE_FIELD_ALERT", 2, 1, RAL_W0C, 32'h0);
    ral.define_field("RECOV_ALERT_STS", "CMD_FIFO_RST_FIELD_ALERT", 3, 1, RAL_W0C, 32'h0);
    ral.define_field("RECOV_ALERT_STS", "EDN_BUS_CMP_ALERT", 12, 1, RAL_W0C, 32'h0);
    ral.define_field("RECOV_ALERT_STS", "CSRNG_ACK_ERR", 13, 1, RAL_W0C, 32'h0);
    ral.define_reg("ERR_CODE", 32'h0000003C, RAL_RO, 32'h00000000);
    ral.define_field("ERR_CODE", "SFIFO_RESCMD_ERR", 0, 1, RAL_RO, 32'h0);
    ral.define_field("ERR_CODE", "SFIFO_GENCMD_ERR", 1, 1, RAL_RO, 32'h0);
    ral.define_field("ERR_CODE", "EDN_ACK_SM_ERR", 20, 1, RAL_RO, 32'h0);
    ral.define_field("ERR_CODE", "EDN_MAIN_SM_ERR", 21, 1, RAL_RO, 32'h0);
    ral.define_field("ERR_CODE", "EDN_CNTR_ERR", 22, 1, RAL_RO, 32'h0);
    ral.define_field("ERR_CODE", "FIFO_WRITE_ERR", 28, 1, RAL_RO, 32'h0);
    ral.define_field("ERR_CODE", "FIFO_READ_ERR", 29, 1, RAL_RO, 32'h0);
    ral.define_field("ERR_CODE", "FIFO_STATE_ERR", 30, 1, RAL_RO, 32'h0);
    ral.define_reg("ERR_CODE_TEST", 32'h00000040, RAL_RW, 32'h00000000);
    ral.define_field("ERR_CODE_TEST", "ERR_CODE_TEST", 0, 5, RAL_RW, 32'h0);
    ral.define_reg("MAIN_SM_STATE", 32'h00000044, RAL_RO, 32'h00000000);
    ral.define_field("MAIN_SM_STATE", "MAIN_SM_STATE", 0, 9, RAL_RO, 32'hC1);
  endfunction
endpackage
