// Auto-generated by appC_earlgrey/tools/reggen_actor.py
// Source: adc_ctrl.hjson
// DO NOT EDIT: regenerate with `reggen_actor.py adc_ctrl.hjson`

package adc_ctrl_ral_defs_pkg;
  import actor_ral_pkg::*;

  function void define_adc_ctrl_ral(RalActor ral);
    ral.define_reg("INTR_STATE", 32'h00000000, RAL_W1C, 32'h00000000);
    ral.define_field("INTR_STATE", "match_pending", 0, 1, RAL_RW, 32'h0);
    ral.define_reg("INTR_ENABLE", 32'h00000004, RAL_RW, 32'h00000000);
    ral.define_field("INTR_ENABLE", "match_pending", 0, 1, RAL_RW, 32'h0);
    ral.define_reg("INTR_TEST", 32'h00000008, RAL_WO, 32'h00000000);
    ral.define_field("INTR_TEST", "match_pending", 0, 1, RAL_WO, 32'h0);
    ral.define_reg("ALERT_TEST", 32'h0000000C, RAL_WO, 32'h00000000);
    ral.define_field("ALERT_TEST", "fatal_fault", 0, 1, RAL_WO, 32'h0);
    ral.define_reg("adc_en_ctl", 32'h00000010, RAL_RW, 32'h00000000);
    ral.define_field("adc_en_ctl", "adc_enable", 0, 1, RAL_RW, 32'h0);
    ral.define_field("adc_en_ctl", "oneshot_mode", 1, 1, RAL_RW, 32'h0);
    ral.define_reg("adc_pd_ctl", 32'h00000014, RAL_RW, 32'h00000000);
    ral.define_field("adc_pd_ctl", "lp_mode", 0, 1, RAL_RW, 32'h0);
    ral.define_field("adc_pd_ctl", "pwrup_time", 4, 4, RAL_RW, 32'h7);
    ral.define_field("adc_pd_ctl", "wakeup_time", 8, 24, RAL_RW, 32'h640);
    ral.define_reg("adc_lp_sample_ctl", 32'h00000018, RAL_RW, 32'h00000000);
    ral.define_field("adc_lp_sample_ctl", "lp_sample_cnt", 0, 8, RAL_RW, 32'h4);
    ral.define_reg("adc_sample_ctl", 32'h0000001C, RAL_RW, 32'h0000009B);
    ral.define_field("adc_sample_ctl", "np_sample_cnt", 0, 16, RAL_RW, 32'h0);
    ral.define_reg("adc_fsm_rst", 32'h00000020, RAL_RW, 32'h00000000);
    ral.define_field("adc_fsm_rst", "rst_en", 0, 1, RAL_RW, 32'h0);
    ral.define_reg("adc_wakeup_ctl", 32'h00000024, RAL_RW, 32'h00000000);
    ral.define_field("adc_wakeup_ctl", "MATCH_EN", 0, 32, RAL_RW, 32'h0);
    ral.define_field("adc_wakeup_ctl", "TRANS_EN", 0, 32, RAL_RW, 32'h0);
    ral.define_reg("filter_status", 32'h00000028, RAL_W1C, 32'h00000000);
    ral.define_field("filter_status", "MATCH", 0, 8, RAL_W1C, 32'h0);
    ral.define_field("filter_status", "TRANS", 0, 32, RAL_W1C, 32'h0);
    ral.define_reg("adc_intr_ctl", 32'h0000002C, RAL_RW, 32'h00000000);
    ral.define_field("adc_intr_ctl", "MATCH_EN", 0, 32, RAL_RW, 32'h0);
    ral.define_field("adc_intr_ctl", "TRANS_EN", 0, 32, RAL_RW, 32'h0);
    ral.define_field("adc_intr_ctl", "ONESHOT_EN", 0, 32, RAL_RW, 32'h0);
    ral.define_reg("adc_intr_status", 32'h00000030, RAL_W1C, 32'h00000000);
    ral.define_field("adc_intr_status", "MATCH", 0, 32, RAL_W1C, 32'h0);
    ral.define_field("adc_intr_status", "TRANS", 0, 32, RAL_W1C, 32'h0);
    ral.define_field("adc_intr_status", "ONESHOT", 0, 32, RAL_W1C, 32'h0);
    ral.define_reg("adc_fsm_state", 32'h00000034, RAL_RO, 32'h00000000);
    ral.define_field("adc_fsm_state", "state", 0, 5, RAL_RO, 32'h0);
  endfunction
endpackage
