// Auto-generated by appC_earlgrey/tools/reggen_actor.py
// Source: spi_host.hjson
// DO NOT EDIT: regenerate with `reggen_actor.py spi_host.hjson`

package spi_host_ral_defs_pkg;
  import actor_ral_pkg::*;

  function void define_spi_host_ral(RalActor ral);
    ral.define_reg("INTR_STATE", 32'h00000000, RAL_W1C, 32'h00000000);
    ral.define_field("INTR_STATE", "error", 0, 1, RAL_RW, 32'h0);
    ral.define_field("INTR_STATE", "spi_event", 1, 1, RAL_RW, 32'h0);
    ral.define_reg("INTR_ENABLE", 32'h00000004, RAL_RW, 32'h00000000);
    ral.define_field("INTR_ENABLE", "error", 0, 1, RAL_RW, 32'h0);
    ral.define_field("INTR_ENABLE", "spi_event", 1, 1, RAL_RW, 32'h0);
    ral.define_reg("INTR_TEST", 32'h00000008, RAL_WO, 32'h00000000);
    ral.define_field("INTR_TEST", "error", 0, 1, RAL_WO, 32'h0);
    ral.define_field("INTR_TEST", "spi_event", 1, 1, RAL_WO, 32'h0);
    ral.define_reg("ALERT_TEST", 32'h0000000C, RAL_WO, 32'h00000000);
    ral.define_field("ALERT_TEST", "fatal_fault", 0, 1, RAL_WO, 32'h0);
    ral.define_reg("CONTROL", 32'h00000010, RAL_RW, 32'h00000000);
    ral.define_field("CONTROL", "SPIEN", 31, 1, RAL_RW, 32'h0);
    ral.define_field("CONTROL", "SW_RST", 30, 1, RAL_RW, 32'h0);
    ral.define_field("CONTROL", "OUTPUT_EN", 29, 1, RAL_RW, 32'h0);
    ral.define_field("CONTROL", "TX_WATERMARK", 8, 8, RAL_RW, 32'h0);
    ral.define_field("CONTROL", "RX_WATERMARK", 0, 8, RAL_RW, 32'h7F);
    ral.define_reg("STATUS", 32'h00000014, RAL_RO, 32'h00000000);
    ral.define_field("STATUS", "READY", 31, 1, RAL_RO, 32'h0);
    ral.define_field("STATUS", "ACTIVE", 30, 1, RAL_RO, 32'h0);
    ral.define_field("STATUS", "TXFULL", 29, 1, RAL_RO, 32'h0);
    ral.define_field("STATUS", "TXEMPTY", 28, 1, RAL_RO, 32'h0);
    ral.define_field("STATUS", "TXSTALL", 27, 1, RAL_RO, 32'h0);
    ral.define_field("STATUS", "TXWM", 26, 1, RAL_RO, 32'h0);
    ral.define_field("STATUS", "RXFULL", 25, 1, RAL_RO, 32'h0);
    ral.define_field("STATUS", "RXEMPTY", 24, 1, RAL_RO, 32'h0);
    ral.define_field("STATUS", "RXSTALL", 23, 1, RAL_RO, 32'h0);
    ral.define_field("STATUS", "BYTEORDER", 22, 1, RAL_RO, 32'h0);
    ral.define_field("STATUS", "RXWM", 20, 1, RAL_RO, 32'h0);
    ral.define_field("STATUS", "CMDQD", 16, 4, RAL_RO, 32'h0);
    ral.define_field("STATUS", "RXQD", 8, 8, RAL_RO, 32'h0);
    ral.define_field("STATUS", "TXQD", 0, 8, RAL_RO, 32'h0);
    ral.define_reg("CONFIGOPTS", 32'h00000018, RAL_RW, 32'h00000000);
    ral.define_field("CONFIGOPTS", "CPOL", 31, 1, RAL_RW, 32'h0);
    ral.define_field("CONFIGOPTS", "CPHA", 30, 1, RAL_RW, 32'h0);
    ral.define_field("CONFIGOPTS", "FULLCYC", 29, 1, RAL_RW, 32'h0);
    ral.define_field("CONFIGOPTS", "CSNLEAD", 24, 4, RAL_RW, 32'h0);
    ral.define_field("CONFIGOPTS", "CSNTRAIL", 20, 4, RAL_RW, 32'h0);
    ral.define_field("CONFIGOPTS", "CSNIDLE", 16, 4, RAL_RW, 32'h0);
    ral.define_field("CONFIGOPTS", "CLKDIV", 0, 16, RAL_RW, 32'h0);
    ral.define_reg("CSID", 32'h0000001C, RAL_RW, 32'h00000000);
    ral.define_field("CSID", "CSID", 0, 32, RAL_RW, 32'h0);
    ral.define_reg("COMMAND", 32'h00000020, RAL_WO, 32'h00000000);
    ral.define_field("COMMAND", "LEN", 5, 20, RAL_WO, 32'h0);
    ral.define_field("COMMAND", "DIRECTION", 3, 2, RAL_WO, 32'h0);
    ral.define_field("COMMAND", "SPEED", 1, 2, RAL_WO, 32'h0);
    ral.define_field("COMMAND", "CSAAT", 0, 1, RAL_WO, 32'h0);
    ral.define_reg("ERROR_ENABLE", 32'h00000024, RAL_RW, 32'h00000000);
    ral.define_field("ERROR_ENABLE", "CSIDINVAL", 4, 1, RAL_RW, 32'h1);
    ral.define_field("ERROR_ENABLE", "CMDINVAL", 3, 1, RAL_RW, 32'h1);
    ral.define_field("ERROR_ENABLE", "UNDERFLOW", 2, 1, RAL_RW, 32'h1);
    ral.define_field("ERROR_ENABLE", "OVERFLOW", 1, 1, RAL_RW, 32'h1);
    ral.define_field("ERROR_ENABLE", "CMDBUSY", 0, 1, RAL_RW, 32'h1);
    ral.define_reg("ERROR_STATUS", 32'h00000028, RAL_W1C, 32'h00000000);
    ral.define_field("ERROR_STATUS", "ACCESSINVAL", 5, 1, RAL_W1C, 32'h0);
    ral.define_field("ERROR_STATUS", "CSIDINVAL", 4, 1, RAL_W1C, 32'h0);
    ral.define_field("ERROR_STATUS", "CMDINVAL", 3, 1, RAL_W1C, 32'h0);
    ral.define_field("ERROR_STATUS", "UNDERFLOW", 2, 1, RAL_W1C, 32'h0);
    ral.define_field("ERROR_STATUS", "OVERFLOW", 1, 1, RAL_W1C, 32'h0);
    ral.define_field("ERROR_STATUS", "CMDBUSY", 0, 1, RAL_W1C, 32'h0);
    ral.define_reg("EVENT_ENABLE", 32'h0000002C, RAL_RW, 32'h00000000);
    ral.define_field("EVENT_ENABLE", "IDLE", 5, 1, RAL_RW, 32'h0);
    ral.define_field("EVENT_ENABLE", "READY", 4, 1, RAL_RW, 32'h0);
    ral.define_field("EVENT_ENABLE", "TXWM", 3, 1, RAL_RW, 32'h0);
    ral.define_field("EVENT_ENABLE", "RXWM", 2, 1, RAL_RW, 32'h0);
    ral.define_field("EVENT_ENABLE", "TXEMPTY", 1, 1, RAL_RW, 32'h0);
    ral.define_field("EVENT_ENABLE", "RXFULL", 0, 1, RAL_RW, 32'h0);
  endfunction
endpackage
