// Auto-generated by appC_earlgrey/tools/reggen_actor.py
// Source: rom_ctrl.hjson
// DO NOT EDIT: regenerate with `reggen_actor.py rom_ctrl.hjson`

package rom_ctrl_ral_defs_pkg;
  import actor_ral_pkg::*;

  function void define_rom_ctrl_ral(RalActor ral);
    ral.define_reg("ALERT_TEST", 32'h00000000, RAL_WO, 32'h00000000);
    ral.define_field("ALERT_TEST", "fatal", 0, 1, RAL_WO, 32'h0);
    ral.define_reg("FATAL_ALERT_CAUSE", 32'h00000004, RAL_RO, 32'h00000000);
    ral.define_field("FATAL_ALERT_CAUSE", "checker_error", 0, 1, RAL_RO, 32'h0);
    ral.define_field("FATAL_ALERT_CAUSE", "integrity_error", 1, 1, RAL_RO, 32'h0);
    ral.define_reg("DIGEST_0", 32'h00000008, RAL_RO, 32'h00000000);
    ral.define_field("DIGEST_0", "DIGEST", 0, 32, RAL_RO, 32'h0);
    ral.define_reg("DIGEST_1", 32'h0000000C, RAL_RO, 32'h00000000);
    ral.define_field("DIGEST_1", "DIGEST", 0, 32, RAL_RO, 32'h0);
    ral.define_reg("DIGEST_2", 32'h00000010, RAL_RO, 32'h00000000);
    ral.define_field("DIGEST_2", "DIGEST", 0, 32, RAL_RO, 32'h0);
    ral.define_reg("DIGEST_3", 32'h00000014, RAL_RO, 32'h00000000);
    ral.define_field("DIGEST_3", "DIGEST", 0, 32, RAL_RO, 32'h0);
    ral.define_reg("DIGEST_4", 32'h00000018, RAL_RO, 32'h00000000);
    ral.define_field("DIGEST_4", "DIGEST", 0, 32, RAL_RO, 32'h0);
    ral.define_reg("DIGEST_5", 32'h0000001C, RAL_RO, 32'h00000000);
    ral.define_field("DIGEST_5", "DIGEST", 0, 32, RAL_RO, 32'h0);
    ral.define_reg("DIGEST_6", 32'h00000020, RAL_RO, 32'h00000000);
    ral.define_field("DIGEST_6", "DIGEST", 0, 32, RAL_RO, 32'h0);
    ral.define_reg("DIGEST_7", 32'h00000024, RAL_RO, 32'h00000000);
    ral.define_field("DIGEST_7", "DIGEST", 0, 32, RAL_RO, 32'h0);
    ral.define_reg("EXP_DIGEST_0", 32'h00000028, RAL_RO, 32'h00000000);
    ral.define_field("EXP_DIGEST_0", "DIGEST", 0, 32, RAL_RO, 32'h0);
    ral.define_reg("EXP_DIGEST_1", 32'h0000002C, RAL_RO, 32'h00000000);
    ral.define_field("EXP_DIGEST_1", "DIGEST", 0, 32, RAL_RO, 32'h0);
    ral.define_reg("EXP_DIGEST_2", 32'h00000030, RAL_RO, 32'h00000000);
    ral.define_field("EXP_DIGEST_2", "DIGEST", 0, 32, RAL_RO, 32'h0);
    ral.define_reg("EXP_DIGEST_3", 32'h00000034, RAL_RO, 32'h00000000);
    ral.define_field("EXP_DIGEST_3", "DIGEST", 0, 32, RAL_RO, 32'h0);
    ral.define_reg("EXP_DIGEST_4", 32'h00000038, RAL_RO, 32'h00000000);
    ral.define_field("EXP_DIGEST_4", "DIGEST", 0, 32, RAL_RO, 32'h0);
    ral.define_reg("EXP_DIGEST_5", 32'h0000003C, RAL_RO, 32'h00000000);
    ral.define_field("EXP_DIGEST_5", "DIGEST", 0, 32, RAL_RO, 32'h0);
    ral.define_reg("EXP_DIGEST_6", 32'h00000040, RAL_RO, 32'h00000000);
    ral.define_field("EXP_DIGEST_6", "DIGEST", 0, 32, RAL_RO, 32'h0);
    ral.define_reg("EXP_DIGEST_7", 32'h00000044, RAL_RO, 32'h00000000);
    ral.define_field("EXP_DIGEST_7", "DIGEST", 0, 32, RAL_RO, 32'h0);
  endfunction
endpackage
